# The 2017 13" MacBook Pro (MacBookPro14,1) breaks Thunderbolt on every
# lid-close suspend. Three separate causes, two of them Linux bugs, one Apple
# firmware behavior (details: https://github.com/omacom/omarchy/issues/10593):
#
#  - In the default deep (S3) sleep the PCI core saves the Alpine Ridge
#    bridges' config space after the thunderbolt driver has already put the
#    chip to sleep, so resume restores garbage: 75-107 s wakeups, dead
#    Thunderbolt and USB-C.
#  - Entering S3 with anything plugged into a Thunderbolt port makes the
#    Mac's EFI resume script disable the Thunderbolt root port entirely;
#    only a cold boot brings it back. No kernel change can prevent this,
#    which is why the machine must default to s2idle.
#  - In s2idle the PCI core skips config-space restore (skip_bus_pm), but
#    this controller genuinely loses its config space during sleep, so it
#    comes back dead there too.
#
# tb-ar-shim-dkms fixes the two kernel-side bugs (config saved early, restored
# on resume; being submitted upstream as PCI quirks), and the limine drop-in
# makes s2idle the default sleep mode so the EFI path can never fire.
# Validated on MacBookPro14,1: 28/28 suspend cycles, 1.3 s resume.
# MacBookPro14,2/14,3 share the controller but are unvalidated, so this gates
# on the exact model.

if omarchy-hw-macbookpro14-1; then
  echo "Detected MacBookPro14,1; fixing Thunderbolt suspend"

  omarchy-pkg-add linux-headers tb-ar-shim-dkms

  # The module autoloads by PCI modalias at boot, but on a live system that
  # coldplug event has already passed — load it now so the first suspend
  # after this script is already protected.
  sudo modprobe tb_ar_shim || true

  sudo mkdir -p /etc/limine-entry-tool.d
  sudo tee /etc/limine-entry-tool.d/macbookpro14-1-thunderbolt.conf >/dev/null <<'EOF'
# Generated by Omarchy installer for MacBookPro14,1 Thunderbolt support.
# Deep (S3) sleep with a Thunderbolt device attached lets the Mac's EFI
# resume script disable the Thunderbolt root port until the next cold boot;
# s2idle never runs that script.
KERNEL_CMDLINE[default]+=" mem_sleep_default=s2idle"
EOF

  # Take effect before the next reboot too
  echo s2idle | sudo tee /sys/power/mem_sleep >/dev/null || true
fi
