# Detect T2 MacBook models using PCI IDs
# Vendor: 106b (Apple), Device IDs: 1801 or 1802 (T2 Security Chip)
if lspci -nn | grep "106b:180[12]" >/dev/null; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  omarchy-pkg-add \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware \
    t2fanrd \
    msr-tools

  # Enable T2 fan control
  systemctl enable t2fanrd.service

  mkdir -p /etc/modules-load.d
  {
    echo "t2bce_vhci"
    echo "hci_bcm4377"
  } > /etc/modules-load.d/t2.conf

  # linux-t2 7.1.4 replaced the apple-bce driver with t2bce; t2bce_vhci is the
  # virtual USB host controller the internal keyboard hangs off, and mkinitcpio
  # pulls t2bce_core/t2bce_dma in via module dependencies.
  mkdir -p /etc/mkinitcpio.conf.d
  echo "MODULES+=(t2bce_vhci usbhid hid_apple hid_generic xhci_pci xhci_hcd)" > \
    /etc/mkinitcpio.conf.d/apple-t2.conf

  # The SMC can leave the external PROCHOT line asserted, which pins every core
  # at its minimum frequency. Clear BD PROCHOT at boot and after each resume so
  # the CPU ignores it.
  install -Dm644 "$OMARCHY_PATH/default/systemd/system/omarchy-t2-prochot.service" \
    /etc/systemd/system/omarchy-t2-prochot.service
  systemctl enable omarchy-t2-prochot.service

  mkdir -p /etc/limine-entry-tool.d
  cat > /etc/limine-entry-tool.d/t2-mac.conf <<'EOF'
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+=" intel_iommu=on iommu=pt pm_async=off mem_sleep_default=deep"
EOF

  # t2fanrd only reads sections for detected fans, so Fan2 is harmless on
  # single-fan models and required on dual-fan MacBooks.
  cat > /etc/t2fand.conf <<'EOF'
[Fan1]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false

[Fan2]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false
EOF
fi
