# The 2013–2015 Apple USB Card Reader (05ac:8406) often stays powered off after
# suspend. usbcore is built into the Arch kernel, so /etc/modprobe.d cannot set
# usbcore.autosuspend; the quirk has to live on the kernel command line.
# ACPI SPWR/SRST (via acpi_call) re-powers the chip when USB reset cannot.

if omarchy-hw-apple-sd-reader; then
  echo "Detected Apple USB SD card reader Mac: $(cat "${OMARCHY_DMI_PRODUCT_NAME:-/sys/class/dmi/id/product_name}" 2>/dev/null || true)"

  limine_conf="${OMARCHY_APPLE_SD_LIMINE_CONF:-/etc/limine-entry-tool.d/apple-sd-reader.conf}"
  udev_rules="${OMARCHY_APPLE_SD_UDEV_RULES:-/etc/udev/rules.d/90-omarchy-apple-sd-reader.rules}"
  sleep_hook="${OMARCHY_APPLE_SD_SLEEP_HOOK:-/usr/lib/systemd/system-sleep/omarchy-apple-sd-reader}"

  omarchy-pkg-add acpi_call

  sudo mkdir -p "$(dirname "$limine_conf")" "$(dirname "$udev_rules")" "$(dirname "$sleep_hook")"

  sudo tee "$limine_conf" >/dev/null <<'EOF'
# Generated by Omarchy for the Apple USB Card Reader (05ac:8406)
KERNEL_CMDLINE[default]+=" usbcore.quirks=05ac:8406:bk usbcore.autosuspend=-1"
EOF

  sudo tee "$udev_rules" >/dev/null <<'EOF'
# Pin the Apple USB Card Reader awake once firmware enumerates it.
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="8406", TEST=="power/control", ATTR{power/control}="on"
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="8406", TEST=="power/autosuspend", ATTR{power/autosuspend}="-1"
EOF

  sudo tee "$sleep_hook" >/dev/null <<'EOF'
#!/bin/bash
# After suspend the Apple USB SD reader often stays detached.
if [[ $1 == "post" ]]; then
  /usr/share/omarchy/bin/omarchy-cmd-apple-sd-reader reset >/dev/null 2>&1 || true
fi
EOF
  sudo chmod 0755 "$sleep_hook"

  if omarchy-cmd-present limine-mkinitcpio; then
    sudo limine-mkinitcpio
  fi

  if omarchy-cmd-present udevadm; then
    sudo udevadm control --reload
    sudo udevadm trigger --subsystem-match=usb --action=add >/dev/null 2>&1 || true
  fi

  omarchy-state set reboot-required
fi
