# Night Transit — Omarchy 4 base theme
accent = "#f06f65"
active_border_color = "#f06f65"
active_tab_background = "#245168"
cursor = "#fff4dc"
foreground = "#f8e5c5"
background = "#112b4d"
selection_foreground = "#112b4d"
selection_background = "#f06f65"

color0 = "#0b203b"
color1 = "#f06f65"
color2 = "#55905c"
color3 = "#d39a30"
color4 = "#4b82c5"
color5 = "#8e67ae"
color6 = "#39a3aa"
color7 = "#f8e5c5"
color8 = "#7896a3"
color9 = "#f07a6d"
color10 = "#64aa6d"
color11 = "#f9b639"
color12 = "#5899e8"
color13 = "#a87acd"
color14 = "#43c0c9"
color15 = "#fff4dc"

mode = "dark"
bg = "#112b4d"
lighter_bg = "#193c5b"
selection = "#245168"
muted = "#7896a3"
dark_fg = "#b8c9c5"
fg = "#f8e5c5"
light_fg = "#f8e5c5"
bright_fg = "#fff4dc"
red = "#d55751"
green = "#55905c"
yellow = "#d39a30"
blue = "#4b82c5"
magenta = "#8e67ae"
cyan = "#39a3aa"
orange = "#e17b3b"
brown = "#8b604d"
dark_bg = "#0b203b"
darker_bg = "#0b203b"
bright_red = "#f07a6d"
bright_green = "#64aa6d"
bright_yellow = "#f9b639"
bright_blue = "#5899e8"
bright_magenta = "#a87acd"
bright_cyan = "#43c0c9"
