# Embed Qualcomm device trees so systemd-stub can select one from SMBIOS data.
# DeviceTreeAuto requires literal paths, so hardware setup refreshes the list.

if omarchy-hw-aarch64-qualcomm; then
  omarchy-pkg-add systemd-ukify

  # Arch Linux ARM's kernel keeps every board's device trees in /boot/dtbs.
  # Omarchy's own kernel keeps its Snapdragon ones under its package name, and
  # those come first, so the trees match the kernel that boots.
  dtb_root=${OMARCHY_QUALCOMM_DTB_ROOT:-/boot/dtbs}
  dtb_dir=$dtb_root/qcom
  for kernel_dtb_dir in "$dtb_root"/linux-omarchy*/qcom; do
    if [[ -d $kernel_dtb_dir ]]; then
      dtb_dir=$kernel_dtb_dir
      break
    fi
  done
  dtb_dir=${OMARCHY_QUALCOMM_DTB_DIR:-$dtb_dir}
  uki_config=${OMARCHY_QUALCOMM_UKI_CONFIG:-/etc/kernel/uki.conf}
  dtbs=()
  for dtb in "$dtb_dir"/x1*.dtb "$dtb_dir"/hamoa*.dtb \
    "$dtb_dir"/glymur*.dtb "$dtb_dir"/sc8280xp*.dtb; do
    if [[ -f $dtb && $dtb != *-el2.dtb ]]; then
      dtbs+=("$dtb")
    fi
  done

  if ((${#dtbs[@]} == 0)); then
    echo "No Windows-on-ARM device trees under $dtb_dir; the UKI gets no .dtbauto sections" >&2
  else
    managed_begin="# BEGIN OMARCHY QUALCOMM DEVICE TREES"
    managed_end="# END OMARCHY QUALCOMM DEVICE TREES"

    mkdir -p "$(dirname "$uki_config")"
    uki_tmp=$(mktemp "${uki_config}.XXXXXX")

    if [[ -f $uki_config ]]; then
      cp -p "$uki_config" "$uki_tmp"
      awk -v begin="$managed_begin" -v end="$managed_end" '
        $0 == begin { managed = 1; next }
        managed && $0 == end { managed = 0; next }
        !managed { print }
      ' "$uki_config" >"$uki_tmp"
    else
      chmod 0644 "$uki_tmp"
    fi

    {
      echo "$managed_begin"
      echo "# Generated by Omarchy for Qualcomm Snapdragon devices."
      echo "# systemd-stub selects a device tree from SMBIOS data."
      echo "# After a kernel update adds new boards, rerun 'omarchy apply hardware'"
      echo "# and rebuild the UKI with 'sudo limine-mkinitcpio'."
      echo "[UKI]"
      echo "DeviceTreeAuto=${dtbs[*]}"
      echo "$managed_end"
    } >>"$uki_tmp"

    if [[ -f $uki_config ]] && cmp -s "$uki_tmp" "$uki_config"; then
      rm -f "$uki_tmp"
    else
      mv -f "$uki_tmp" "$uki_config"
      # The UKI carries the trees once it is rebuilt. An image's first boot
      # rebuilds after its last step, but does not watch this file.
      if [[ -n ${OMARCHY_IMAGE_BOOT_REBUILD:-} ]]; then
        : >"$OMARCHY_IMAGE_BOOT_REBUILD"
      fi
    fi
    echo "Listed ${#dtbs[@]} device trees in $uki_config"
  fi
fi
