# Embed Qualcomm device trees so systemd-stub can select one from SMBIOS data.
# DeviceTreeAuto requires literal paths, so hardware setup refreshes the list.

if omarchy-hw-qualcomm-soc; then
  omarchy-pkg-add systemd-ukify

  dtb_dir=${OMARCHY_QUALCOMM_DTB_DIR:-/boot/dtbs/qcom}
  uki_config=${OMARCHY_QUALCOMM_UKI_CONFIG:-/etc/kernel/uki.conf}
  dtbs=()
  for dtb in "$dtb_dir"/x1*.dtb "$dtb_dir"/hamoa*.dtb \
    "$dtb_dir"/glymur*.dtb "$dtb_dir"/sc8280xp*.dtb; do
    if [[ -f $dtb && $dtb != *-el2.dtb ]]; then
      dtbs+=("$dtb")
    fi
  done

  if ((${#dtbs[@]} == 0)); then
    echo "No Windows-on-ARM device trees under $dtb_dir; the UKI gets no .dtbauto sections" >&2
  else
    managed_begin="# BEGIN OMARCHY QUALCOMM DEVICE TREES"
    managed_end="# END OMARCHY QUALCOMM DEVICE TREES"

    mkdir -p "$(dirname "$uki_config")"
    uki_tmp=$(mktemp "${uki_config}.XXXXXX")

    if [[ -f $uki_config ]]; then
      cp -p "$uki_config" "$uki_tmp"
      awk -v begin="$managed_begin" -v end="$managed_end" '
        $0 == begin { managed = 1; next }
        managed && $0 == end { managed = 0; next }
        !managed { print }
      ' "$uki_config" >"$uki_tmp"
    else
      chmod 0644 "$uki_tmp"
    fi

    {
      echo
      echo "$managed_begin"
      echo "# Generated by Omarchy for Qualcomm Snapdragon devices."
      echo "# systemd-stub selects a device tree from SMBIOS data."
      echo "# Rerun 'omarchy apply hardware' after a kernel update adds new boards."
      echo "[UKI]"
      echo "DeviceTreeAuto=${dtbs[*]}"
      echo "$managed_end"
    } >>"$uki_tmp"

    mv -f "$uki_tmp" "$uki_config"
    echo "Listed ${#dtbs[@]} device trees in $uki_config"
  fi
fi
