# Snapdragon laptops boot with the device tree that describes the exact model,
# and their Windows-on-ARM firmware provides none. A systemd-stub UKI can carry
# every candidate as a .dtbauto section and pick the right one at boot from the
# machine's SMBIOS hardware ids (the .hwids section ukify builds from systemd's
# tables). mkinitcpio hands ukify /etc/kernel/uki.conf when it exists, so listing
# the device trees there makes every UKI limine-mkinitcpio-hook builds pick its
# own tree, on this machine and after every kernel update.
#
# Limitation: DeviceTreeAuto= takes literal paths, not globs, so this is a
# snapshot of /boot/dtbs/qcom from when the leaf ran. A kernel update that adds
# a new board's tree needs `omarchy apply hardware` to refresh the list. Retire
# the enumeration when ukify accepts globs in DeviceTreeAuto=.
#
# Same prefixes as the Omarchy ISO's live UKI: Snapdragon X Elite/Plus (x1*),
# X2 (hamoa*, glymur*) and 8cx Gen 3 (sc8280xp*). The -el2 variants exist for
# running the kernel at EL2, which this firmware does not.

if omarchy-hw-qualcomm-soc; then
  omarchy-pkg-add systemd-ukify

  dtbs=()
  for dtb in /boot/dtbs/qcom/x1*.dtb /boot/dtbs/qcom/hamoa*.dtb \
    /boot/dtbs/qcom/glymur*.dtb /boot/dtbs/qcom/sc8280xp*.dtb; do
    if [[ -f $dtb && $dtb != *-el2.dtb ]]; then
      dtbs+=("$dtb")
    fi
  done

  if ((${#dtbs[@]} == 0)); then
    echo "No Windows-on-ARM device trees under /boot/dtbs/qcom; the UKI gets no .dtbauto sections" >&2
  else
    mkdir -p /etc/kernel
    {
      echo "# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/dtb-uki.sh)."
      echo "# Device trees the systemd-stub picks from at boot by SMBIOS hardware id."
      echo "# Rerun 'omarchy apply hardware' after a kernel update adds new boards."
      echo "[UKI]"
      echo "DeviceTreeAuto=${dtbs[*]}"
    } >/etc/kernel/uki.conf
    echo "Listed ${#dtbs[@]} device trees in /etc/kernel/uki.conf"
  fi
fi
