# Firmware for the Qualcomm SoC.
#
# Arch Linux ARM splits the redistributable Qualcomm blobs out of
# linux-firmware into linux-firmware-qcom (Adreno GPU microcode, Wi-Fi and
# Bluetooth board data); without it the GPU and Wi-Fi never come up.
#
# The blobs signed by the laptop vendor (GPU zap shader, audio and compute DSP
# images) are not redistributable. qcom-firmware-extract copies the ones this
# machine's device tree names from the owner's own Windows installation: the
# ISO staged them before the disk was written, and a free-space install still
# has the Windows partition on disk. The installer builds the boot image once
# after every hardware leaf has run, so nothing is rebuilt here.
#
# Until the audio DSP firmware is present its driver cannot load; the failing
# probe resets the USB-C mux, which drops a root disk attached over USB-C and
# hangs the boot. Keep the driver blacklisted while that firmware is absent;
# the file is removed once the firmware is installed (re-run
# `sudo qcom-firmware-extract` after providing it).

if omarchy-hw-qualcomm-soc; then
  omarchy-pkg-add linux-firmware-qcom qcom-firmware-extract

  qcom-firmware-extract --install --no-rebuild

  mkdir -p /etc/modprobe.d
  if qcom-firmware-extract --list-missing | grep -q 'adsp'; then
    cat >/etc/modprobe.d/qualcomm-adsp-nofw.conf <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/firmware.sh)
# No signed audio-DSP firmware is installed yet; the driver's failing probe
# resets the USB-C mux and can take a USB-C root disk down with it. Removed
# by the same leaf once the firmware is present.
blacklist qcom_q6v5_pas
CONF
  else
    rm -f /etc/modprobe.d/qualcomm-adsp-nofw.conf
  fi
fi
