# Firmware for the Qualcomm SoC. Arch Linux ARM splits the redistributable
# Qualcomm blobs out of linux-firmware into linux-firmware-qcom (Adreno GPU
# microcode, Wi-Fi/Bluetooth board data); without it the GPU and Wi-Fi never
# come up. The device-specific blobs signed by the laptop vendor (GPU zap
# shader, audio/compute DSP, WLAN/BT) are not redistributable and are
# extracted from the owner's Windows partition instead (qcom-firmware-extract).
#
# Until those signed blobs are present the audio DSP driver cannot load its
# firmware; its probe resets the USB-C mux while it fails, which drops a root
# disk attached over USB-C and hangs the boot. Keep it blacklisted while the
# DSP firmware is absent; the file is removed when the blobs are installed.

if omarchy-hw-qualcomm-soc; then
  omarchy-pkg-add linux-firmware-qcom

  mkdir -p /etc/modprobe.d
  if compgen -G '/usr/lib/firmware/updates/qcom/*/adsp*' >/dev/null ||
    compgen -G '/usr/lib/firmware/qcom/*/*/adsp*' >/dev/null; then
    rm -f /etc/modprobe.d/qualcomm-adsp-nofw.conf
  else
    cat >/etc/modprobe.d/qualcomm-adsp-nofw.conf <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/firmware.sh)
# No signed audio-DSP firmware is installed yet; the driver's failing probe
# resets the USB-C mux and can take a USB-C root disk down with it. Removed
# by the same leaf once the firmware is present.
blacklist qcom_q6v5_pas
CONF
  fi
fi
