# Firmware for the Qualcomm SoC.
#
# Arch Linux ARM splits the redistributable Qualcomm blobs out of
# linux-firmware into linux-firmware-qcom (Adreno GPU microcode, Wi-Fi and
# Bluetooth board data); without it the GPU and Wi-Fi never come up.
#
# The blobs signed by the laptop vendor (GPU zap shader, audio and compute DSP
# images) are not redistributable. qcom-firmware-extract copies the ones this
# machine's device tree names from the owner's own Windows installation: the
# ISO staged them before the disk was written, and a free-space install still
# has the Windows partition on disk. The installer builds the boot image once
# after every hardware leaf has run, so nothing is rebuilt here.
#
# Until the audio DSP firmware is present its driver cannot load; the failing
# probe resets the USB-C mux, which drops a root disk attached over USB-C and
# hangs the boot. Keep the driver blacklisted while that firmware is absent;
# the file is removed once the firmware is installed (re-run
# `sudo qcom-firmware-extract` after providing it).

if omarchy-hw-qualcomm-soc; then
  omarchy-pkg-add linux-firmware-qcom qcom-firmware-extract

  qcom-firmware-extract --install --no-rebuild

  modprobe_dir=${OMARCHY_QUALCOMM_MODPROBE_DIR:-/etc/modprobe.d}
  root_source=$(findmnt -no SOURCE --nofsroot / 2>/dev/null || true)

  mkdir -p "$modprobe_dir"
  if [[ -n $root_source ]] && lsblk -sno TRAN "$root_source" 2>/dev/null | grep -q '^usb$'; then
    # Root disk on USB. When the DSPs boot with real firmware the Type-C port
    # controller (pmic_glink/UCSI) takes over the ports and resets them, which
    # drops a root disk behind a USB-C port (observed on the HP EliteBook Ultra
    # G1q, JimmayVV/omarchy-iso#27). Keep the DSPs off on such installs: no
    # audio or battery reporting, but the system boots. RETIRE when the kernel
    # stops resetting an already-connected port (#27).
    cat >"$modprobe_dir/qualcomm-adsp-nofw.conf" <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/firmware.sh)
# The root disk is attached over USB. Booting the DSPs hands the USB-C ports
# to the port controller, which resets them and drops the root disk. Keep the
# DSP driver off on this install (no audio or battery reporting) until the
# kernel stops resetting connected ports; delete this file after moving the
# system to an internal disk.
blacklist qcom_q6v5_pas
CONF
  elif qcom-firmware-extract --list-missing | grep -q 'adsp'; then
    cat >"$modprobe_dir/qualcomm-adsp-nofw.conf" <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/firmware.sh)
# No signed audio-DSP firmware is installed yet; the driver's failing probe
# resets the USB-C mux and can take a USB-C root disk down with it. Removed
# by the same leaf once the firmware is present.
blacklist qcom_q6v5_pas
CONF
  else
    rm -f "$modprobe_dir/qualcomm-adsp-nofw.conf"
  fi
fi
