# Name the platform drivers a Snapdragon laptop needs before its disk, keyboard and panel work.

mkinitcpio_dir=${OMARCHY_QUALCOMM_MKINITCPIO_DIR:-/etc/mkinitcpio.conf.d}

if omarchy-hw-aarch64-qualcomm; then
  mkdir -p "$mkinitcpio_dir"
  cat >"$mkinitcpio_dir/qualcomm-platform.conf" <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices.
# Pin control, interconnect, PMIC and bus drivers of the X1 chips. Arch Linux
# ARM's kernel builds them in. A kernel that builds them as modules needs them
# named here, since mkinitcpio's hooks only pick storage, input and display
# drivers. The ? skips one that a kernel does not have.
MODULES+=(pinctrl-x1e80100? qnoc-x1e80100? spmi-pmic-arb? pinctrl-spmi-gpio? i2c-qcom-geni?
  reset-gpio? gpio-shared-proxy? qcom_hwspinlock? smem? smp2p? socinfo? nvmem_qfprom?
  nvmem_qcom-spmi-sdam? qcom-cpucp-mbox? pci-pwrctrl-pwrseq? pwrseq-qcom-wcn? dwc3-qcom?
  rtc-pm8xxx? qcom-pon? pm8941-pwrkey? icc-bwmon? qcom_tsens? qcom-spmi-temp-alarm?)
CONF
fi
