# Add firmware workarounds required by current Snapdragon laptops.

DROP_IN="/etc/limine-entry-tool.d/qualcomm-snapdragon.conf"

if omarchy-hw-qualcomm-soc; then
  mkdir -p /etc/limine-entry-tool.d
  cat >"$DROP_IN" <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices.
# Keep display and I/O resources enabled until their drivers load.
# Disable pointer authentication and waiting for an unavailable TPM.
KERNEL_CMDLINE[default]+=" clk_ignore_unused pd_ignore_unused arm64.nopauth systemd.tpm2_wait=0"
CONF
fi
