# Kernel parameters Snapdragon laptops need under their Windows-on-ARM firmware:
# the set Fedora's Snapdragon images and archiso carry, measured on the HP
# EliteBook Ultra G1q (X1E-78-100). Retire each one when the kernel no longer
# needs it; Fedora's images are the tell.

DROP_IN="/etc/limine-entry-tool.d/qualcomm-snapdragon.conf"

if omarchy-hw-qualcomm-soc; then
  mkdir -p /etc/limine-entry-tool.d
  cat >"$DROP_IN" <<'CONF'
# Generated by Omarchy for Qualcomm Snapdragon devices (install/hardware/qualcomm/kernel-params.sh)
#   clk_ignore_unused pd_ignore_unused -- display and I/O drivers load from the
#     initramfs after the kernel would otherwise switch their clocks and power
#     domains off; the screen goes dark at 15 s without them.
#   arm64.nopauth -- pointer authentication faults under this firmware.
#   systemd.tpm2_wait=0 -- the firmware advertises a TPM2 Linux never gets;
#     without this, a 90 s wait for /dev/tpmrm0 on every boot.
KERNEL_CMDLINE[default]+=" clk_ignore_unused pd_ignore_unused arm64.nopauth systemd.tpm2_wait=0"
CONF
fi
