# The Spark firmware clears memory as it is freed, and Limine frees the ~124 GB
# it claimed before starting a UKI, leaving the screen black for ~20 seconds.
# Boot the kernel directly until Limine stops that, then remove this and rebuild:
# https://github.com/Limine-Bootloader/Limine/issues/673
limine_config_dir=${OMARCHY_LIMINE_CONFIG_DIR:-/etc/limine-entry-tool.d}
config_file=$limine_config_dir/zz-omarchy-dgx-spark.conf

if omarchy-hw-aarch64-gb10 && omarchy-hw-match "NVIDIA_DGX_Spark"; then
  # Direct Boot loads the UKI through firmware. ENABLE_UKI=no makes the next
  # rebuild delete that file. Skip the drop-in, and remove one an earlier run
  # wrote, so a later kernel rebuild keeps the firmware entry's target.
  direct_boot_status=0
  omarchy-boot-direct || direct_boot_status=$?
  if (( direct_boot_status == 0 )); then
    rm -f "$config_file"
    echo "Keeping the UKI because Omarchy Direct Boot is configured"
  elif (( direct_boot_status == 1 )); then
    mkdir -p "$limine_config_dir"
    # Named to sort after omarchy-uki.conf, whose ENABLE_UKI=yes this overrides.
    cat >"$config_file" <<'CONF'
# Generated by Omarchy for the NVIDIA DGX Spark: boot without a UKI to avoid a
# 20-second firmware delay. Remove once Limine fixes
# https://github.com/Limine-Bootloader/Limine/issues/673
ENABLE_UKI=no
CONF
  else
    echo "Couldn't read EFI boot entries; leaving the DGX Spark UKI setting unchanged" >&2
  fi
fi
