mode = "dark"
accent = "#67d8ed"
background = "#0d1218"
dark_background = "#090e13"
darker_background = "#070b10"
lighter_background = "#18232c"
foreground = "#d6e3e9"
dark_foreground = "#7b939f"
light_foreground = "#e0edf2"
bright_foreground = "#f0f8fa"
selection = "#234552"
selection_background = "#234552"
selection_foreground = "#f0f8fa"
muted = "#78919e"
red = "#ec8894"
green = "#8fcaa0"
yellow = "#d9bd82"
orange = "#dca078"
blue = "#7eb9dc"
magenta = "#b3a4d5"
purple = "#b3a4d5"
cyan = "#67d8ed"
brown = "#a08b7a"
bright_red = "#f3a4ae"
bright_green = "#b5ddbc"
bright_yellow = "#ead19e"
bright_blue = "#a5d8ef"
bright_magenta = "#cfc1e7"
bright_cyan = "#b0ecf5"
hyprland_active_border = "rgba(67d8eddd)"
hyprland_inactive_border = "rgba(2b3d49aa)"
