# Fix Thunderbolt suspend on the MacBookPro14,1: install the tb-ar-shim DKMS
# module and default the machine to s2idle sleep, then rebuild boot images so
# the cmdline change reaches the Limine entries.
# Same logic as install/hardware/apple/fix-thunderbolt-suspend.sh; see
# https://github.com/omacom/omarchy/issues/10593 for the investigation.

if omarchy-hw-macbookpro14-1; then
  echo "Detected MacBookPro14,1; fixing Thunderbolt suspend"

  omarchy-pkg-add linux-headers tb-ar-shim-dkms

  # The module autoloads by PCI modalias at boot, but on a live system that
  # coldplug event has already passed — load it now so the first suspend
  # after this migration is already protected.
  sudo modprobe tb_ar_shim || true

  sudo mkdir -p /etc/limine-entry-tool.d
  sudo tee /etc/limine-entry-tool.d/macbookpro14-1-thunderbolt.conf >/dev/null <<'EOF'
# Generated by Omarchy installer for MacBookPro14,1 Thunderbolt support.
# Deep (S3) sleep with a Thunderbolt device attached lets the Mac's EFI
# resume script disable the Thunderbolt root port until the next cold boot;
# s2idle never runs that script.
KERNEL_CMDLINE[default]+=" mem_sleep_default=s2idle"
EOF

  # Take effect before the reboot too
  echo s2idle | sudo tee /sys/power/mem_sleep >/dev/null || true

  if ! grep -q "mem_sleep_default=s2idle" /proc/cmdline; then
    if command -v limine-mkinitcpio >/dev/null 2>&1; then
      sudo limine-mkinitcpio
    fi
  fi
fi
