echo "Let selected monospace fonts override the packaged default"

fontconfig_file="$HOME/.config/fontconfig/fonts.conf"

[[ -f $fontconfig_file ]] || exit 0

font_name=$(sed -n '/<string>monospace<\/string>/,/<\/match>/ {
  /<string>monospace<\/string>/d
  s|.*<string>\(.*\)</string>.*|\1|p
}' "$fontconfig_file")

[[ -n $font_name ]] || exit 0

staged=$(mktemp "$fontconfig_file.XXXXXX")
trap 'rm -f "$staged"' EXIT

cat >"$staged" <<XML
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test name="family" qual="any">
      <string>monospace</string>
    </test>
    <edit name="family" mode="prepend_first" binding="strong">
      <string>$font_name</string>
    </edit>
  </match>
</fontconfig>
XML

# Only replace the exact file generated by the previous font command. Leave
# administrator- or user-authored Fontconfig rules untouched.
cmp -s "$fontconfig_file" "$staged" || exit 0

cat >"$staged" <<XML
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test name="family" qual="first">
      <string>monospace</string>
    </test>
    <edit name="family" mode="assign" binding="strong">
      <string>$font_name</string>
    </edit>
  </match>
</fontconfig>
XML

chmod --reference="$fontconfig_file" "$staged"
mv "$staged" "$fontconfig_file"
trap - EXIT
