# Schedule night light by location: write ~/.config/hypr/hyprsunset.conf with
# sunrise/sunset profiles at the user's location, and start hyprsunset so the
# schedule takes effect on this login.
#
# Idempotent: re-running is a no-op unless the user's stored location changes
# or hyprsunset.conf is missing. Skipped silently on headless / non-TTY runs
# that cannot reach a network (e.g. an offline `omarchy update`).

set -euo pipefail

NL_CONF="$HOME/.config/hypr/hyprsunset.conf"
NL_BIN="omarchy-toggle-nightlight"

# Skip if a non-default hyprsunset.conf already exists — the user has either
# run --setup themselves or hand-edited. Either way, do not clobber.
if [[ -f $NL_CONF ]] && ! grep -q '^# Generated by .omarchy toggle nightlight --setup' "$NL_CONF"; then
  exit 0
fi

# If we have a recorded location, run non-interactively (this is the common
# case: user already set weather location, or this is a re-run of the
# migration). Otherwise, on a TTY, the script itself will print a hint and
# the user can run `omarchy toggle nightlight --setup` themselves. We do not
# block the migration on an interactive prompt.
"$NL_BIN" --setup || true
