PACKAGE_NAME="macbook-ec-wake"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="macbook_ec_wake_trial"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
