LogLevel  3
LogDir  "default"
DefaultVolume 100
DefaultModule espeak-ng
SymbolsPreproc "char"
SymbolsPreprocFile "gender-neutral.dic"
SymbolsPreprocFile "font-variants.dic"
SymbolsPreprocFile "symbols.dic"
SymbolsPreprocFile "emojis.dic"
SymbolsPreprocFile "orca.dic"
SymbolsPreprocFile "orca-chars.dic"
SymbolsPreprocFile "orca-math.dic"
Include "/etc/speech-dispatcher/clients/*.conf"
