#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT

# Load the production functions without self-elevation or the reset entrypoint.
awk '
  /^[a-z_]+\(\) \{/ { copying = 1 }
  copying { print }
  /^}/ { copying = 0 }
' "$ROOT/bin/omarchy-system-factory-reset" >"$test_tmp/functions"

OLD_ID=11111111111111111111111111111111
NEW_ID=22222222222222222222222222222222
FOREIGN_ID=33333333333333333333333333333333

# Runs one production function against a disposable root; `fail` exits
# non-zero like the real one, so callers can assert on refusals.
run_reset_function() {
  bash -c '
    set -euo pipefail
    source "$1/functions"
    log() { :; }
    fail() { printf "%s\n" "$1" >&2; exit 1; }
    shift
    "$@"
  ' _ "$test_tmp" "$@"
}

make_root() {
  local root="$1"
  mkdir -p "$root/etc" "$root/boot/EFI/Linux" "$root/boot/$OLD_ID" "$root/boot/$FOREIGN_ID" \
    "$root/usr/share/omarchy/default/limine"
  printf '%s\n' "$NEW_ID" >"$root/etc/machine-id"
  printf 'old\n' >"$root/boot/$OLD_ID/initramfs"
  printf 'foreign\n' >"$root/boot/$FOREIGN_ID/marker"
  cat >"$root/usr/share/omarchy/default/limine/limine.conf" <<'EOF'
### Shipped template
default_entry: 2
interface_branding: Omarchy Bootloader
EOF
}

omarchy_entry() {
  cat <<EOF
/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
comment: Omarchy
comment: machine-id=$1 order-priority=50
  //linux-omarchy
  ### This kernel entry is auto-generated by limine-entry-tool
  comment: kernel-id=linux-omarchy
  protocol: efi
  path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#stalehash
  //Snapshots
    ///1 │ 2026-09-01 00:00:00
    protocol: efi
    path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#stalehash

EOF
}

windows_entry() {
  cat <<'EOF'
/Windows
    protocol: efi
    path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
EOF
}

foreign_entry() {
  cat <<EOF
/+Other Linux
comment: machine-id=$FOREIGN_ID order-priority=50
  //linux
  protocol: efi
  path: boot():/EFI/Linux/other_linux.efi#foreignhash

EOF
}

# The OS entry block that carries the given machine-id, as limine.conf holds it.
entry_for() {
  awk -v id="$2" '
    /^\/[^\/]/ { if (mine) printf "%s", block; block = ""; mine = 0 }
    { block = block $0 "\n" }
    $0 ~ ("^comment: machine-id=" id "([[:space:]]|$)") { mine = 1 }
    END { if (mine) printf "%s", block }' "$1"
}

# ------------------------------------------------------------- shared ESP

root="$test_tmp/shared"
make_root "$root"
{
  printf '### Seller settings\ntimeout: 10\ndefault_entry: 2\n'
  omarchy_entry "$OLD_ID"
  windows_entry
  foreign_entry
} >"$root/boot/limine.conf"
windows_before=$(windows_entry)
foreign_before=$(foreign_entry)

run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a shared limine.conf"
conf="$root/boot/limine.conf"

grep -q '^### Shipped template$' "$conf" && ! grep -q 'timeout: 10' "$conf" ||
  fail "global settings start over from the shipped template"
[[ $(grep -m1 '^/' "$conf") == "/+Omarchy" ]] ||
  fail "this installation's entry keeps its first position, where default_entry points"
entry_for "$conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "this installation's entry is re-keyed to the new machine-id"
! grep -q "$OLD_ID" "$conf" || fail "the previous machine-id leaves limine.conf"
! grep -q 'stalehash' "$conf" || fail "the stale kernel and snapshot entries are dropped"
[[ $(awk '/^\/Windows$/,/bootmgfw/' "$conf") == "$windows_before" ]] ||
  fail "the Windows entry survives unchanged"
[[ $(awk '/^\/\+Other Linux$/,/foreignhash/' "$conf") == "$(grep -v '^$' <<<"$foreign_before")" ]] ||
  fail "another installation's entry survives unchanged"
[[ -f $root/boot/$OLD_ID/initramfs ]] ||
  fail "the previous identity's boot directory stays until the rebuilt entry verifies"
run_reset_function commit_esp_staging "$root/boot" "$OLD_ID" "$NEW_ID" ||
  fail "a verified staging commits"
[[ ! -e $root/boot/$OLD_ID ]] || fail "committing removes the previous identity's boot directory"
[[ -f $root/boot/$FOREIGN_ID/marker ]] || fail "another installation's boot directory survives"
pass "a shared ESP keeps other systems' entries and directories while this entry is re-keyed in place"

# ------------------------------------------------- failed staging and retry

# Stages against an ESP the way rebuild_next_boot does, with the production
# cleanup trap armed and the staged root in place; $2 is what happens after
# limine-update rewrote the ESP.
stage_esp() {
  local root="$1" outcome="$2"
  mkdir -p "$root/top/@omarchy-reset-next"
  run_reset_function eval "
    trap cleanup EXIT
    TOP_MNT=$root/top
    NEXT_NAME=@omarchy-reset-next
    ESP_MNT=$test_tmp/no-esp-mount
    esp_backup=\$(mktemp -d $test_tmp/esp-backup.XXXXXX)
    backup_esp $root/boot \$esp_backup
    esp_new_id=$NEW_ID
    esp_restore=$root/boot
    reset_limine_config $root /boot $OLD_ID
    printf 'factory uki\n' >$root/boot/EFI/Linux/omarchy_linux-omarchy.efi
    printf 'factory limine\n' >$root/boot/EFI/limine/limine_x64.efi
    printf 'factory-only kernel\n' >$root/boot/EFI/Linux/omarchy_linux-lts.efi
    mkdir -p $root/boot/EFI/BOOT $root/boot/$NEW_ID
    printf 'factory fallback\n' >$root/boot/EFI/BOOT/BOOTX64.EFI
    $outcome
  "
}

root="$test_tmp/failed"
make_root "$root"
mkdir -p "$root/boot/EFI/limine"
printf 'running uki\n' >"$root/boot/EFI/Linux/omarchy_linux-omarchy.efi"
printf 'running limine\n' >"$root/boot/EFI/limine/limine_x64.efi"
{
  printf 'default_entry: 2\n'
  omarchy_entry "$OLD_ID"
  windows_entry
  foreign_entry
} >"$root/boot/limine.conf"
cp -r "$root/boot" "$test_tmp/failed-esp-before"

# log fails too: errexit still applies in the cleanup trap, so a failing
# message must not stop the restore or the backup's removal.
if stage_esp "$root" "log() { return 1; }; fail 'limine.conf hash does not match the rebuilt file'" 2>/dev/null; then
  fail "the simulated staging failure aborts the reset"
fi
diff -r "$test_tmp/failed-esp-before" "$root/boot" >/dev/null ||
  fail "a failed staging restores the running system's limine.conf, UKI, bootloader and directories, and drops what the rebuild added"
! compgen -G "$test_tmp/esp-backup.*" >/dev/null || fail "a restored backup is discarded"
pass "a failed staging leaves the running system's boot files as they were"

run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "a retry rewrites the restored limine.conf"
[[ $(grep -c '^/+Omarchy$' "$root/boot/limine.conf") == 1 ]] &&
  [[ $(grep -m1 '^/' "$root/boot/limine.conf") == "/+Omarchy" ]] &&
  entry_for "$root/boot/limine.conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "a retry re-keys the running system's own entry, still first"
pass "a retry after a failed staging starts from the running system's own entry"

root="$test_tmp/verified"
make_root "$root"
mkdir -p "$root/boot/EFI/limine"
printf 'running uki\n' >"$root/boot/EFI/Linux/omarchy_linux-omarchy.efi"
printf 'running limine\n' >"$root/boot/EFI/limine/limine_x64.efi"
{ omarchy_entry "$OLD_ID"; windows_entry; } >"$root/boot/limine.conf"
stage_esp "$root" "commit_esp_staging $root/boot $OLD_ID $NEW_ID" ||
  fail "a verified staging completes"
[[ $(cat "$root/boot/EFI/Linux/omarchy_linux-omarchy.efi") == "factory uki" ]] &&
  entry_for "$root/boot/limine.conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "a verified staging keeps the rebuilt boot files"
[[ ! -e $root/boot/$OLD_ID && -d $root/boot/$NEW_ID ]] ||
  fail "a verified staging hands the ESP over to the new identity"
! compgen -G "$test_tmp/esp-backup.*" >/dev/null || fail "a committed backup is discarded"
pass "a verified staging keeps its changes and discards the backup"

root="$test_tmp/signalled"
make_root "$root"
mkdir -p "$root/boot/EFI/limine"
printf 'running uki\n' >"$root/boot/EFI/Linux/omarchy_linux-omarchy.efi"
{ omarchy_entry "$OLD_ID"; windows_entry; } >"$root/boot/limine.conf"
if stage_esp "$root" "mv $root/top/@omarchy-reset-next $root/top/@; kill -TERM \$\$" 2>/dev/null; then
  fail "the simulated signal stops the reset"
fi
[[ $(cat "$root/boot/EFI/Linux/omarchy_linux-omarchy.efi") == "factory uki" ]] &&
  entry_for "$root/boot/limine.conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "a signal after the root switch leaves the factory root its own boot files"
! compgen -G "$test_tmp/esp-backup.*" >/dev/null || fail "a backup the switch made obsolete is discarded"
pass "a signal right after the root switch keeps the factory root's boot files"

# Until the factory root is in place, the running root is still what boots,
# so a failed unmount or rename must still restore the running system's files.
function_body() {
  awk -v name="$1" '$0 ~ ("^" name "\\(\\) \\{") { copying = 1 } copying { print } copying && /^}/ { exit }' \
    "$ROOT/bin/omarchy-system-factory-reset"
}
! function_body rebuild_next_boot | grep -q commit_ &&
  function_body commit_next_boot | grep -q commit_esp_staging &&
  function_body stage_full_reset | awk '/swap_done=1/ { swapped = 1 } /commit_next_boot/ { found = 1; ordered = swapped; exit } END { exit !(found && ordered) }' ||
  fail "boot-file recovery stays armed until the factory root is switched in"
pass "boot-file recovery stays armed until the factory root is switched in"

# ------------------------------------------------------- Omarchy-only ESP

root="$test_tmp/single"
make_root "$root"
omarchy_entry "$OLD_ID" >"$root/boot/limine.conf"
run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a single-system limine.conf"
[[ $(grep -c '^/' "$root/boot/limine.conf") == 1 ]] &&
  entry_for "$root/boot/limine.conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "a single-system ESP ends with one re-keyed Omarchy entry"
pass "a single-system ESP ends with one empty entry for the new identity"

# ------------------------------------------------------ duplicated entry

root="$test_tmp/duplicate"
make_root "$root"
{ omarchy_entry "$OLD_ID"; windows_entry; omarchy_entry "$OLD_ID"; } >"$root/boot/limine.conf"
run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a limine.conf with a duplicated entry"
[[ $(grep -c "machine-id=$NEW_ID" "$root/boot/limine.conf") == 1 ]] ||
  fail "a duplicated previous entry becomes exactly one entry for the new identity"
grep -q '^/Windows$' "$root/boot/limine.conf" || fail "Windows survives next to a duplicated entry"
pass "a duplicated previous entry collapses into one re-keyed entry"

# ----------------------------------------------------------- no template

root="$test_tmp/no-template"
make_root "$root"
rm "$root/usr/share/omarchy/default/limine/limine.conf"
omarchy_entry "$OLD_ID" >"$root/boot/limine.conf"
if run_reset_function reset_limine_config "$root" /boot "$OLD_ID" 2>/dev/null; then
  fail "reset refuses to continue without a limine.conf template"
fi
pass "reset refuses to continue without a limine.conf template"

# ----------------------------------------------------- hash verification

root="$test_tmp/verify"
make_root "$root"
printf 'rebuilt uki\n' >"$root/boot/EFI/Linux/omarchy_linux-omarchy.efi"
uki_hash=$(b2sum "$root/boot/EFI/Linux/omarchy_linux-omarchy.efi" | cut -d' ' -f1)
write_verified_conf() {
  {
    printf 'default_entry: 2\n/+Omarchy\ncomment: machine-id=%s order-priority=50 \n' "$NEW_ID"
    printf '  //linux-omarchy\n  path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#%s\n' "$1"
    windows_entry
    foreign_entry
  } >"$root/boot/limine.conf"
}

write_verified_conf "$uki_hash"
run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null ||
  fail "another installation's unverifiable UKI does not block the reset"
write_verified_conf "0000"
if run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null; then
  fail "a stale hash on this installation's rebuilt UKI blocks the reset"
fi
printf 'default_entry: 2\n/+Omarchy\ncomment: machine-id=%s order-priority=50 \n' "$NEW_ID" >"$root/boot/limine.conf"
if run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null; then
  fail "an entry with no rebuilt UKI blocks the reset"
fi
pass "hash verification covers exactly this installation's rebuilt entry"

# ------------------------------------------------ first-boot provisioning

if ! unshare --user --map-root-user --mount true 2>/dev/null; then
  skip "no unprivileged mount namespace; skipping first-boot boot entry checks"
  exit 0
fi

# Only the boot entry functions: the script's top level draws its UI.
awk '
  /^(esp_path|limine_entries_stale|reset_limine_config)\(\) \{/ { copying = 1 }
  copying { print }
  /^}/ { copying = 0 }
' "$ROOT/bin/omarchy-provision-owner" >"$test_tmp/provision-functions"
[[ $(grep -c '^[a-z_]*() {' "$test_tmp/provision-functions") == 3 ]] ||
  fail "the first-boot boot entry functions can be loaded"

# omarchy-provision-owner reads /etc/machine-id directly, so give it this
# test's identity in a private mount namespace.
run_provision_function() {
  local root="$1"
  shift
  printf '%s\n' "$NEW_ID" >"$test_tmp/machine-id"
  unshare --user --map-root-user --mount bash -c '
    set -euo pipefail
    test_tmp=$1 root=$2
    shift 2
    mount --bind "$test_tmp/machine-id" /etc/machine-id
    source "$test_tmp/provision-functions"
    esp_path() { echo "$root/boot"; }
    log_step() { :; }
    OMARCHY_PATH="$root/usr/share/omarchy"
    "$@"
  ' _ "$test_tmp" "$root" "$@"
}

# Prints the verdict, so a broken harness cannot pass for "not stale".
staleness() {
  run_provision_function "$1" bash -c 'true' >/dev/null || fail "the first-boot harness runs"
  run_provision_function "$1" eval 'if limine_entries_stale; then echo stale; else echo fresh; fi'
}

root="$test_tmp/first-boot"
make_root "$root"
{
  printf 'default_entry: 2\n'
  omarchy_entry "$NEW_ID"
  windows_entry
  foreign_entry
} >"$root/boot/limine.conf"

[[ $(staleness "$root") == fresh ]] ||
  fail "first boot leaves entries alone when this machine already owns one"
pass "other systems' machine-ids do not make first boot rebuild the boot entries"

run_provision_function "$root" reset_limine_config ||
  fail "first boot rebuilds a shared limine.conf"
conf="$root/boot/limine.conf"
[[ $(grep -m1 '^/' "$conf") == "/+Omarchy" ]] && entry_for "$conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "first boot keeps this machine's entry first, where default_entry points"
! grep -q 'stalehash' "$conf" || fail "first boot drops this machine's stale kernel entries"
[[ $(awk '/^\/Windows$/,/bootmgfw/' "$conf") == "$windows_before" ]] ||
  fail "first boot keeps the Windows entry"
entry_for "$conf" "$FOREIGN_ID" | grep -q 'foreignhash' && [[ -f $root/boot/$FOREIGN_ID/marker ]] ||
  fail "first boot keeps another installation's entry and directory"
pass "a first-boot rebuild keeps other systems' entries and empties only this machine's"

# The rebuild's limine-update failed here: only this machine's header is left.
[[ $(staleness "$root") == stale ]] ||
  fail "first boot retries a rebuild that left this machine's entry without kernels"
pass "a machine whose entry lost its kernels gets them back at the next first boot"

printf 'default_entry: 2\n' >"$root/boot/limine.conf"
{ windows_entry; foreign_entry; } >>"$root/boot/limine.conf"
[[ $(staleness "$root") == stale ]] ||
  fail "first boot repairs a machine left without an entry of its own"
pass "a machine without an entry of its own still gets one at first boot"
