#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

prune="$ROOT/bin/omarchy-limine-prune-missing-entries"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

# An ESP as archinstall + Omarchy leave it after a kernel update: the Omarchy
# UKI is there, archinstall's arch-linux.efi is long gone, and its hand-written
# entry still sits at the top of the menu where the timeout selects it.
new_boot() {
  local boot="$tmp_dir/$1"

  rm -rf "$boot"
  mkdir -p "$boot/EFI/Linux"
  touch "$boot/EFI/Linux/omarchy_linux.efi"
  printf '%s\n' "$boot"
}

archinstall_config() {
  cat <<'CONF'
timeout: 5
interface_branding_color: 9ece6a

/Arch Linux (linux)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: root=/dev/mapper/root rw rootflags=subvol=@ rootfstype=btrfs
/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
    comment: Omarchy
    //Omarchy (linux)
        protocol: efi
        path: boot():/EFI/Linux/omarchy_linux.efi#4c516ba8
CONF
}

boot=$(new_boot stale)
config="$boot/limine.conf"
archinstall_config >"$config"

"$prune" "$config" "$boot" >/dev/null || fail "pruning a stale entry succeeds"

if grep -F 'arch-linux.efi' "$config" >/dev/null; then
  fail "the stale archinstall entry is removed" "$(cat "$config")"
fi
if grep -Fx '/Arch Linux (linux)' "$config" >/dev/null; then
  fail "the stale entry's title is removed" "$(cat "$config")"
fi
pass "an entry whose UKI is missing from the ESP is removed"

grep -Fx '/+Omarchy' "$config" >/dev/null || fail "the Omarchy entry survives" "$(cat "$config")"
grep -F 'omarchy_linux.efi#4c516ba8' "$config" >/dev/null ||
  fail "the Omarchy entry keeps its hashed path" "$(cat "$config")"
grep -Fx 'timeout: 5' "$config" >/dev/null || fail "global directives survive" "$(cat "$config")"
grep -Fx '### This OS entry is auto-generated by limine-entry-tool' "$config" >/dev/null ||
  fail "the auto-generated marker survives" "$(cat "$config")"
pass "every other line is left byte for byte"

# The content hash after # is limine-entry-tool's, not part of the filename;
# stripping it is what lets a present UKI be recognised as present.
head -n1 "$config" >/dev/null
[[ $(head -n1 "$config") == "timeout: 5" ]] || fail "the file does not gain a leading blank line"
pass "the rewritten config keeps its first line"

# Running again is a no-op: there is nothing left whose image is missing.
before=$(cat "$config")
"$prune" "$config" "$boot" >/dev/null || fail "a second run succeeds"
[[ $(cat "$config") == "$before" ]] || fail "a second run changes nothing" "$(cat "$config")"
pass "pruning is idempotent"

# An entry pointing at a UKI that is present must never be touched, even when a
# sibling is pruned in the same pass.
boot=$(new_boot present)
config="$boot/limine.conf"
archinstall_config >"$config"
touch "$boot/EFI/Linux/arch-linux.efi"
"$prune" "$config" "$boot" >/dev/null || fail "a config with nothing to prune succeeds"
grep -F 'arch-linux.efi' "$config" >/dev/null ||
  fail "an entry whose UKI is present is kept" "$(cat "$config")"
pass "an entry whose UKI is present on the ESP is kept"

# Only boot():/ can be mapped to a file. uuid()/guid()/hdd() name a volume this
# cannot resolve, so those entries are never anyone's to remove.
boot=$(new_boot resolver)
config="$boot/limine.conf"
cat >"$config" <<'CONF'
timeout: 5

/Other OS
    protocol: efi
    path: uuid(12345678-1234-1234-1234-123456789abc):/EFI/other/grubx64.efi
/+Omarchy
    //Omarchy (linux)
        protocol: efi
        path: boot():/EFI/Linux/omarchy_linux.efi
CONF
"$prune" "$config" "$boot" >/dev/null || fail "an unresolvable path succeeds"
grep -F 'uuid(12345678' "$config" >/dev/null ||
  fail "an entry on an unresolvable volume is kept" "$(cat "$config")"
pass "an entry whose volume cannot be resolved is kept"

# Emptying the menu would leave nothing to boot, which is worse than the stale
# entry this exists to remove.
boot=$(new_boot empty)
config="$boot/limine.conf"
cat >"$config" <<'CONF'
timeout: 5

/Arch Linux (linux)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
/Arch Linux (linux-lts)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux-lts.efi
CONF
before=$(cat "$config")
if "$prune" "$config" "$boot" >/dev/null 2>&1; then
  fail "a config with no surviving entry is reported, not rewritten"
fi
[[ $(cat "$config") == "$before" ]] ||
  fail "a config with no surviving entry is left alone" "$(cat "$config")"
pass "a config whose every entry is missing is left alone and reported"

# A branch entry's own path is not the child's; removing the branch would take
# a bootable child with it.
boot=$(new_boot branch)
config="$boot/limine.conf"
cat >"$config" <<'CONF'
timeout: 5

/+Omarchy
    path: boot():/EFI/Linux/gone.efi
    //Omarchy (linux)
        protocol: efi
        path: boot():/EFI/Linux/omarchy_linux.efi
CONF
"$prune" "$config" "$boot" >/dev/null || fail "a branch entry succeeds"
grep -F 'omarchy_linux.efi' "$config" >/dev/null ||
  fail "a branch carrying nested entries is kept" "$(cat "$config")"
pass "a branch entry carrying nested entries is kept"
