#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"
test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT
test_home="$test_tmp/home"
stub_bin="$test_tmp/bin"
mkdir -p "$test_home" "$stub_bin"

cat >"$stub_bin/mise" <<'STUB'
#!/bin/bash
printf '%s:%s\n' "${MISE_MINIMUM_RELEASE_AGE-unset}" "$*" >>"$MISE_TEST_LOG"
if [[ ${1:-} == "which" ]]; then printf '%s\n' "$MISE_TEST_AGENT"; fi
STUB
cat >"$test_tmp/agent" <<'STUB'
#!/bin/bash
printf '%s:%s\n' "${MISE_MINIMUM_RELEASE_AGE-unset}" "$*"
STUB
chmod +x "$stub_bin/mise"
chmod +x "$test_tmp/agent"
export HOME="$test_home" PATH="$stub_bin:$ROOT/bin:$PATH" MISE_TEST_LOG="$test_tmp/calls"
"$ROOT/bin/omarchy-mise-install" npm:playwright playwright

for age in unset 7d 0; do
  : >"$MISE_TEST_LOG"
  if [[ $age == "unset" ]]; then
    unset MISE_MINIMUM_RELEASE_AGE
  else
    export MISE_MINIMUM_RELEASE_AGE=$age
  fi
  "$test_home/.local/bin/playwright" --version
  "$ROOT/bin/omarchy-update-mise" >/dev/null
  [[ $(<"$MISE_TEST_LOG") == "$age:use -g --quiet npm:playwright"$'\n'"$age:x npm:playwright -- playwright --version"$'\n'"$age:up" ]] ||
    fail "wrappers and updates preserve release-age policy $age" "$(<"$MISE_TEST_LOG")"
  pass "wrappers and updates preserve release-age policy $age"
  : >"$MISE_TEST_LOG"
  # A PATH containing only mocks guarantees no installed host agent can run.
  output=$(PATH="$stub_bin" GROK_HOME="$test_home/grok" MISE_TEST_AGENT="$test_tmp/agent" "$ROOT/bin/omarchy-agent-account-exec" grok --version)
  [[ $output == "$age:--version" ]] || fail "first-run account dispatch overwrote release-age policy $age" "$output"
  [[ $(<"$MISE_TEST_LOG") == "$age:use -g --quiet grok"$'\n'"$age:which grok" ]] || fail "account dispatch did not preserve release-age policy during installation"
  pass "first-run account dispatch preserves release-age policy $age"
done

# Existing installations need the same policy change, but only for unmodified
# launchers generated by Omarchy. No tool is installed during the migration.
wrapper="$test_home/.local/bin/playwright"
sed -i '1a export MISE_MINIMUM_RELEASE_AGE=0' "$wrapper"
cp "$wrapper" "$test_home/.local/bin/custom"
echo 'echo keep-me' >>"$test_home/.local/bin/custom"
cp "$wrapper" "$test_home/.local/bin/explicit-age"
sed -i 's/MINIMUM_RELEASE_AGE=0/MINIMUM_RELEASE_AGE=14/' "$test_home/.local/bin/explicit-age"
ln -s playwright "$test_home/.local/bin/symlink"
cp "$test_home/.local/bin/custom" "$test_tmp/custom-before"
cp "$test_home/.local/bin/explicit-age" "$test_tmp/explicit-before"
: >"$MISE_TEST_LOG"
bash -euo pipefail "$ROOT/migrations/1791640215.sh" >/dev/null
if grep -q MISE_MINIMUM_RELEASE_AGE "$wrapper"; then fail "migration left the generated forced override"; fi
cmp "$test_home/.local/bin/custom" "$test_tmp/custom-before" || fail "migration modified a custom wrapper"
cmp "$test_home/.local/bin/explicit-age" "$test_tmp/explicit-before" || fail "migration modified an explicit user age"
[[ -L $test_home/.local/bin/symlink && -x $wrapper ]] || fail "migration changed symlink or executable semantics"
[[ ! -s $MISE_TEST_LOG ]] || fail "migration must not invoke mise or install tools"
cp "$wrapper" "$test_tmp/wrapper-after"
bash -euo pipefail "$ROOT/migrations/1791640215.sh" >/dev/null
cmp "$wrapper" "$test_tmp/wrapper-after" || fail "migration is not idempotent"
pass "migration repairs exact generated wrappers without executing tools or changing custom launchers"
