#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"
require_command jq

test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT
test_home="$test_tmp/home"
mock_bin="$test_tmp/bin"
inventory="$test_tmp/inventory.json"
log="$test_tmp/calls"
mkdir -p "$test_home/.config/omarchy/defaults" "$mock_bin"

cat >"$mock_bin/mise" <<'SH'
#!/bin/bash
printf '%s\n' "$*" >>"$OMARCHY_TEST_LOG"
case "$1" in
  ls)
    [[ ${OMARCHY_TEST_INVENTORY_FAIL:-false} == "false" ]] || exit 2
    cat "$OMARCHY_TEST_INVENTORY"
    ;;
  where) exit 1 ;; # A missing selected version must not hide installed versions.
  rm) [[ ${OMARCHY_TEST_REMOVE_FAIL:-false} == "false" ]] ;;
  uninstall)
    [[ ${OMARCHY_TEST_UNINSTALL_FAIL:-false} == "false" ]] || exit 1
    case ${OMARCHY_TEST_AFTER:-empty} in
      empty) echo '[]' >"$OMARCHY_TEST_INVENTORY" ;;
      remaining) ;;
      malformed) echo invalid >"$OMARCHY_TEST_INVENTORY" ;;
      unavailable) rm -f "$OMARCHY_TEST_INVENTORY" ;;
    esac
    ;;
  *) exit 99 ;;
esac
SH

cat >"$mock_bin/gum" <<'SH'
#!/bin/bash
printf 'gum %s\n' "$*" >>"$OMARCHY_TEST_LOG"
if [[ ${OMARCHY_TEST_REPLACE:-false} == "true" ]]; then
  printf '#!/bin/bash\necho custom\n' >"$HOME/.local/bin/codex"
fi
[[ ${OMARCHY_TEST_CANCEL:-false} == "false" ]]
SH

cat >"$mock_bin/omarchy-pkg-present" <<'SH'
#!/bin/bash
[[ $1 == "hermes-desktop" && ${OMARCHY_TEST_DESKTOP:-false} == "true" ]]
SH
chmod +x "$mock_bin/"*

run_agent() {
  env HOME="$test_home" OMARCHY_PATH="$ROOT" PATH="$mock_bin:$ROOT/bin:$PATH" \
    OMARCHY_TEST_INVENTORY="$inventory" OMARCHY_TEST_LOG="$log" \
    "$ROOT/bin/omarchy-remove-agent" "$@"
}

reset_fixture() {
  rm -f "$test_home/.local/bin/codex"
  env HOME="$test_home" "$ROOT/bin/omarchy-mise-install" codex
  echo '[{"version":"1.0.0","installed":true,"active":false}]' >"$inventory"
  echo codex >"$test_home/.config/omarchy/defaults/agent"
  : >"$log"
}

reset_fixture
run_agent --check codex || fail "an installed version remains visible when the selected version is missing"
[[ $(cat "$log") == 'ls codex --installed --json' ]] || fail "visibility only reads installed versions"
pass "visibility uses the installed inventory, not the selected version"

echo '[]' >"$inventory"
if run_agent --check codex; then fail "a cold launcher is not an installed agent"; fi
echo invalid >"$inventory"
if run_agent --check codex; then fail "malformed inventory does not mark an agent installed"; fi
reset_fixture
if OMARCHY_TEST_INVENTORY_FAIL=true run_agent --check codex; then fail "inventory failure is not installation"; fi
pass "empty, malformed, and unavailable inventories do not offer removal"

for agent in claude crush copilot opencode pi cursor-agent gemini; do
  env HOME="$test_home" "$ROOT/bin/omarchy-mise-install" "$agent"
  run_agent --check "$agent" || fail "$agent recognizes its generated launcher"
done
for pair in 'antigravity-cli agy' 'github:can1357/oh-my-pi omp' 'npm:@xai-official/grok grok' 'github:OpenRouterLabs/ori-releases ori'; do
  read -r package agent <<<"$pair"
  env HOME="$test_home" "$ROOT/bin/omarchy-mise-install" "$package" "$agent"
  : >"$log"
  run_agent --check "$agent" || fail "$agent recognizes its generated launcher"
  grep -Fx "ls $package --installed --json" "$log" >/dev/null || fail "$agent queries its backend package"
done
muse_package='http:muse[url=https://api.meta.ai/muse-launcher.sh,bin=muse,version_list_url=https://api.meta.ai/muse-code/channels/muse-stable,version_json_path=.version]'
env HOME="$test_home" "$ROOT/bin/omarchy-mise-install" "$muse_package" muse
run_agent --check muse || fail "Muse recognizes the HTTP-backend launcher"
pass "all generic agents recognize launchers generated by the real installer"

reset_fixture
sed -i '/^export MISE_MINIMUM_RELEASE_AGE=/d' "$test_home/.local/bin/codex"
run_agent --check codex || fail "older generated launchers remain removable"
pass "older generated launchers remain removable"

for kind in custom symlink; do
  reset_fixture
  if [[ $kind == "custom" ]]; then
    echo custom >"$test_home/.local/bin/codex"
  else
    mv "$test_home/.local/bin/codex" "$test_home/codex-real"
    ln -s "$test_home/codex-real" "$test_home/.local/bin/codex"
  fi
  if run_agent codex >"$test_tmp/output" 2>&1; then fail "$kind launcher cannot be removed"; fi
  [[ -e $test_home/.local/bin/codex && ! -s $log ]] || fail "$kind launcher is untouched"
done
pass "custom launchers and symlinks are never removed"

reset_fixture
if OMARCHY_TEST_CANCEL=true run_agent codex; then fail "cancellation stops removal"; fi
[[ -f $test_home/.local/bin/codex ]] || fail "cancellation keeps the launcher"
! grep -q '^rm\|^uninstall' "$log" || fail "cancellation runs no mise mutation"
grep -F 'Remove all mise-managed versions' "$log" >/dev/null || fail "confirmation explains removal scope"
pass "cancellation preserves the installation"

reset_fixture
if OMARCHY_TEST_REPLACE=true run_agent codex; then fail "a replaced launcher stops removal"; fi
! grep -q '^rm\|^uninstall' "$log" || fail "replacement during confirmation prevents mise mutations"
pass "ownership is rechecked after confirmation"

for failure in remove uninstall remaining malformed unavailable; do
  reset_fixture
  case "$failure" in
    remove) result=OMARCHY_TEST_REMOVE_FAIL=true ;;
    uninstall) result=OMARCHY_TEST_UNINSTALL_FAIL=true ;;
    *) result=OMARCHY_TEST_AFTER=$failure ;;
  esac
  if (export "$result"; run_agent codex) >"$test_tmp/output" 2>&1; then fail "$failure prevents success"; fi
  [[ -f $test_home/.local/bin/codex ]] || fail "$failure retains the launcher"
  [[ $(cat "$test_home/.config/omarchy/defaults/agent") == "codex" ]] || fail "$failure retains the default"
done
pass "failed removal and uncertain verification retain the launcher and default"

reset_fixture
mkdir -p "$test_home/.codex" "$test_home/project"
echo credentials >"$test_home/.codex/auth.json"
echo chat >"$test_home/.codex/session.jsonl"
echo project >"$test_home/project/file"
run_agent codex >/dev/null
[[ ! -e $test_home/.local/bin/codex ]] || fail "successful removal deletes the generated launcher"
[[ ! -e $test_home/.config/omarchy/defaults/agent ]] || fail "successful removal clears the matching default"
grep -Fx 'rm -g --no-prune codex' "$log" >/dev/null || fail "removal clears the global request"
grep -Fx 'uninstall --all codex' "$log" >/dev/null || fail "removal uninstalls the selected tool"
[[ $(cat "$test_home/.codex/auth.json") == "credentials" && $(cat "$test_home/.codex/session.jsonl") == "chat" && $(cat "$test_home/project/file") == "project" ]] || fail "user data stays intact"
pass "successful removal clears the launcher and matching default but preserves user data"

reset_fixture
echo claude >"$test_home/.config/omarchy/defaults/agent"
run_agent codex >/dev/null
[[ $(cat "$test_home/.config/omarchy/defaults/agent") == "claude" ]] || fail "another default agent stays selected"
pass "removing one agent preserves a different default"

reset_fixture
printf '#!/bin/bash\n# Written by omarchy-install-hermes-cli.\n' >"$test_home/.local/bin/hermes"
run_agent --check hermes || fail "the standalone Hermes install is visible"
if OMARCHY_TEST_DESKTOP=true run_agent --check hermes; then fail "Hermes Desktop belongs to Remove AI"; fi
mkdir -p "$test_home/.hermes"
echo memory >"$test_home/.hermes/memory"
echo hermes >"$test_home/.config/omarchy/defaults/agent"
run_agent hermes >/dev/null
[[ ! -e $test_home/.local/bin/hermes && ! -e $test_home/.config/omarchy/defaults/agent ]] || fail "Hermes removal clears its launcher and default"
[[ $(cat "$test_home/.hermes/memory") == "memory" ]] || fail "Hermes removal keeps its data"
grep -Fx 'uninstall --all pipx:hermes-agent[extras=all]' "$log" >/dev/null || fail "Hermes delegates to its existing remover"
pass "standalone Hermes uses its existing remover while desktop Hermes is excluded"

: >"$log"
for agent in '../codex' 'codex;touch nope' openclaw; do
  if run_agent "$agent" >/dev/null 2>&1; then fail "unsupported names are rejected"; fi
done
if run_agent codex extra >/dev/null 2>&1; then fail "extra arguments are rejected"; fi
[[ ! -s $log ]] || fail "invalid input performs no operation"
pass "invalid names and arguments perform no operation"

run_node_test <<'JS'
const fs = require('fs')
const menu = requireFromRoot('shell/plugins/menu/MenuModel.js')
const entries = menu.parseMenuJsonc(fs.readFileSync(path.join(root, 'default/omarchy/omarchy-menu.jsonc'), 'utf8'))
const byId = Object.fromEntries(entries.map(entry => [entry.id, entry]))
const removers = entries.filter(entry => entry.id.startsWith('remove.agents.'))
assertEqual(removers.length, 14, 'the menu covers current mise agents and legacy Gemini')
for (const entry of removers) {
  const agent = entry.id.split('.').at(-1)
  assertEqual(entry.when, `omarchy-remove-agent --check ${agent}`, `${agent} visibility uses the remover`)
  assertEqual(entry.action, `omarchy-launch-floating-terminal-with-presentation omarchy-remove-agent ${agent}`, `${agent} removal opens a confirmation terminal`)
  const source = byId[`setup.default.agent.${agent}`]
  if (source) {
    assertEqual(entry.icon, source.icon, `${agent} uses its branded glyph`)
    assertEqual(entry.iconFont, source.iconFont, `${agent} uses its icon font`)
  }
}
assert(!byId['remove.agents.openclaw'], 'package-managed OpenClaw keeps its existing remover')
JS
