#!/bin/bash

set -euo pipefail

# colors-neovim.toml lets an installed theme carry its Neovim integration back:
# pure TOML data that omarchy serializes into neovim.lua literals, so nothing
# that runs code is shipped or executed. This suite locks the schema, the
# serialization, the escape hatch back to the generic template, and the fact
# that hostile strings stay strings.

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT

home="$test_tmp/home"
state="$home/.local/state/omarchy/current"
themes="$home/.config/omarchy/themes"
mkdir -p "$state" "$themes"

marker="omarchy-colors-neovim-marker"

set_theme() {
  HOME="$home" OMARCHY_PATH="$ROOT" PATH="$ROOT/bin:$PATH" \
    OMARCHY_THEME_HEADLESS=1 OMARCHY_THEME_SKIP_BACKGROUND=1 \
    XDG_RUNTIME_DIR="$test_tmp" \
    bash "$ROOT/bin/omarchy-theme-set" "$1" 2>"$test_tmp/stderr" || return $?
}

staged() {
  printf '%s' "$state/theme/$1"
}

assert_staged() {
  [[ -f $(staged "$1") ]] || fail "$2"
}

render() {
  HOME="$home" OMARCHY_PATH="$ROOT" PATH="$ROOT/bin:$PATH" \
    bash "$ROOT/bin/omarchy-theme-colors-neovim" "$@"
}

write_noir_config() {
  cat >"$1" <<TOML
schema = 1

[[plugins]]
spec = "tahadx/noir.nvim"
priority = 1000
config = true

[plugins.opts]
variant = "dawn"

[[plugins]]
spec = "LazyVim/LazyVim"

[plugins.opts]
colorscheme = "noir"
TOML
}

# An installed theme may not ship neovim.lua, but its declarative integration
# replaces the generated one all the same.
noir="$themes/noir-dawn"
mkdir -p "$noir/.git"
cat >"$noir/colors.toml" <<TOML
mode = "dark"
background = "#1c1c1c"
foreground = "#c1c1c1"
accent = "#8a9a7b"
red = "#8a9a7b"
green = "#c1c1c1"
yellow = "#888888"
blue = "#aaaaaa"
magenta = "#999999"
cyan = "#aa9988"
TOML
write_noir_config "$noir/colors-neovim.toml"
printf 'vim.cmd("%s")\n' "$marker" >"$noir/neovim.lua"

set_theme noir-dawn || fail "omarchy-theme-set applies a theme carrying colors-neovim.toml"

assert_staged colors-neovim.toml "colors-neovim.toml is colour data and is staged"
! grep -q "$marker" "$(staged hyprland.lua)" || fail "an installed theme's hyprland.lua is still dropped"
! grep -q "$marker" "$(staged neovim.lua)" || fail "an installed theme cannot ship neovim.lua itself"
! grep -q "bjarneo/aether" "$(staged neovim.lua)" || fail "colors-neovim.toml replaces the generated default"
grep -q '"tahadx/noir.nvim"' "$(staged neovim.lua)" || fail "the theme's plugin is serialized"
grep -q 'variant = "dawn"' "$(staged neovim.lua)" || fail "plugin opts are serialized"
grep -q 'colorscheme = "noir"' "$(staged neovim.lua)" || fail "a second plugin entry is serialized"

pass "an installed theme's colors-neovim.toml replaces the generated neovim.lua"

golden="$test_tmp/golden.lua"
cat >"$golden" <<'LUA'
-- Neovim integration generated by Omarchy from this theme's colors-neovim.toml.
-- Everything below is data serialized from that TOML; edit the theme's TOML,
-- not this file.

return {
  {
    "tahadx/noir.nvim",
    priority = 1000,
    config = true,
    opts = {
      variant = "dawn",
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "noir",
    },
  },
}
LUA

diff -u "$golden" "$(staged neovim.lua)" || fail "serialization is deterministic and matches the documented shape"

pass "the serialized neovim.lua matches the documented shape exactly"

# A string value that tries to break out of its quotes comes out as one inert
# Lua string, whatever it contains.
hostile="$themes/hostile"
mkdir -p "$hostile/.git"
cp "$noir/colors.toml" "$hostile/colors.toml"
cat >"$hostile/colors-neovim.toml" <<TOML
[[plugins]]
spec = "evil/example"
opts = { injection = "\"]].os.execute(\"$marker\") --" }
TOML

set_theme hostile || fail "omarchy-theme-set applies a theme whose strings try to escape"
grep -qF '\"]].os.execute' "$(staged neovim.lua)" || fail "a hostile value stays inside its quoted string"
! grep -q "^ *$marker" "$(staged neovim.lua)" || fail "a hostile value never becomes code on its own line"

pass "a string that tries to break out of its quotes stays a string"

# Anything the schema does not understand keeps the generated default and says
# so, instead of half-applying a theme's Neovim config.
invalid_toml="$themes/invalid-toml"
mkdir -p "$invalid_toml/.git"
cp "$noir/colors.toml" "$invalid_toml/colors.toml"
printf '[[plugins]\nspec = "unterminated\n' >"$invalid_toml/colors-neovim.toml"

set_theme invalid-toml || fail "an unparsable colors-neovim.toml does not break theme-set"
grep -q "bjarneo/aether" "$(staged neovim.lua)" || fail "an unparsable colors-neovim.toml keeps the generated default"
grep -q "colors-neovim" "$test_tmp/stderr" || fail "an unparsable colors-neovim.toml is named on stderr"

pass "an unparsable colors-neovim.toml falls back to the generated template loudly"

unknown_key="$themes/unknown-key"
mkdir -p "$unknown_key/.git"
cp "$noir/colors.toml" "$unknown_key/colors.toml"
printf 'loadstring = "evil"\n[[plugins]]\nspec = "x/y"\n' >"$unknown_key/colors-neovim.toml"

set_theme unknown-key || fail "an unknown top-level key does not break theme-set"
grep -q "does not support the top-level key" "$test_tmp/stderr" || fail "an unknown top-level key is named on stderr"
grep -q "bjarneo/aether" "$(staged neovim.lua)" || fail "an unknown top-level key keeps the generated default"

pass "keys outside the schema are refused rather than ignored"

bad_schema="$themes/bad-schema"
mkdir -p "$bad_schema/.git"
cp "$noir/colors.toml" "$bad_schema/colors.toml"
printf 'schema = true\n[[plugins]]\nspec = "x/y"\n' >"$bad_schema/colors-neovim.toml"

set_theme bad-schema || fail "a boolean schema value does not break theme-set"
grep -q "unsupported schema version" "$test_tmp/stderr" || fail "a boolean schema value is named on stderr"
grep -q "bjarneo/aether" "$(staged neovim.lua)" || fail "a boolean schema value keeps the generated default"

pass "the schema gate rejects non-integer versions like true"

nospec="$themes/nospec"
mkdir -p "$nospec/.git"
cp "$noir/colors.toml" "$nospec/colors.toml"
printf '[[plugins]]\npriority = 1\n' >"$nospec/colors-neovim.toml"

set_theme nospec || fail "a [[plugins]] entry without a spec does not break theme-set"
grep -q "needs a non-empty spec" "$test_tmp/stderr" || fail "a missing spec is named on stderr"

pass "a [[plugins]] entry without a spec is refused"

# A theme the user wrote gets the same treatment through the same door.
mine="$themes/mine"
mkdir -p "$mine"
cp "$noir/colors.toml" "$mine/colors.toml"
write_noir_config "$mine/colors-neovim.toml"

set_theme mine || fail "omarchy-theme-set applies a user-written theme with colors-neovim.toml"
grep -q '"tahadx/noir.nvim"' "$(staged neovim.lua)" || fail "a user-written theme's colors-neovim.toml is honored"

pass "a user-written theme's colors-neovim.toml is honored too"

# Direct renderer behaviour: the value zoo round-trips as literals, and losing
# python3 degrades to a refusal instead of a broken file.
values_toml="$test_tmp/values.toml"
cat >"$values_toml" <<TOML
schema = 1

[[plugins]]
spec = "x/y"
enabled = false
ratio = 0.35
tags = ["a", "b"]
depth = { of = { nesting = true } }

[plugins.opts]
"weird key" = "tab\tnewline\nquote\"backslash\\\\\\\\"
empty = {}
TOML
values_out="$test_tmp/values-out.lua"
render --file "$values_toml" --out "$values_out" || fail "the renderer reads the documented value zoo"
grep -q 'enabled = false' "$values_out" || fail "booleans serialize"
grep -q 'ratio = 0.35' "$values_out" || fail "floats serialize"
grep -qF '["weird key"] = ' "$values_out" || fail "non-bare keys are bracket-quoted"
grep -qF '"tab\tnewline\nquote\"backslash\\\\"' "$values_out" || fail "control characters are escaped into the string"

pass "strings, numbers, booleans, arrays, nested tables, and odd keys all serialize"

out_without_python="$test_tmp/no-python.lua"
if PATH= "$ROOT/bin/omarchy-theme-colors-neovim" --file "$values_toml" --out "$out_without_python" 2>"$test_tmp/stderr"; then
  fail "the renderer refuses to run without python3"
fi
grep -q "python3" "$test_tmp/stderr" || fail "losing python3 is explained on stderr"
[[ ! -e $out_without_python ]] || fail "nothing is written when the renderer refuses"

pass "without python3 the renderer refuses and writes nothing"

bad_args=0
render --file "$values_toml" 2>/dev/null || bad_args=1
(( bad_args == 1 )) || fail "the renderer requires both --file and --out"

pass "the renderer requires both --file and --out"
