# Pocket Arcade — Omarchy 4 palette
# Pocket Studio / Label Deck

accent = "#db5b78"
active_border_color = "#db5b78"
active_tab_background = "#1d2948"
cursor = "#fff7f0"
foreground = "#eee7e4"
background = "#0b1024"
selection_foreground = "#0b1024"
selection_background = "#db5b78"

color0 = "#0b1024"
color1 = "#db5b78"
color2 = "#4f999c"
color3 = "#dab968"
color4 = "#6484c8"
color5 = "#a96eae"
color6 = "#57b8b7"
color7 = "#eee7e4"
color8 = "#74758f"
color9 = "#f16f8b"
color10 = "#68bbb8"
color11 = "#efd17c"
color12 = "#83a3e5"
color13 = "#c78ac8"
color14 = "#79d0cc"
color15 = "#fff7f0"

mode = "dark"
bg = "#0b1024"
lighter_bg = "#121a34"
selection = "#1d2948"
muted = "#74758f"
dark_fg = "#b1acc0"
fg = "#eee7e4"
light_fg = "#f8f1ed"
bright_fg = "#fff7f0"
red = "#db5b78"
green = "#4f999c"
yellow = "#dab968"
blue = "#6484c8"
magenta = "#a96eae"
cyan = "#57b8b7"
orange = "#e27a83"
brown = "#8b6d9c"
dark_bg = "#060a17"
darker_bg = "#03050b"
bright_red = "#f16f8b"
bright_green = "#68bbb8"
bright_yellow = "#efd17c"
bright_blue = "#83a3e5"
bright_magenta = "#c78ac8"
bright_cyan = "#79d0cc"
