# Managed by Omarchy. Override individual tools in ~/.config/mise/config.toml.

[settings]
system_installs_dir = "~/.local/share/mise/installs"
shims_dir = "~/.local/share/mise/shims"
system_shims_dir = "~/.local/share/mise/shims"

[tools]
codex = { version = "latest", lazy = true, minimum_release_age = "0s" }
claude = { version = "latest", lazy = true, minimum_release_age = "0s" }
crush = { version = "latest", lazy = true, minimum_release_age = "0s" }
antigravity-cli = { version = "latest", lazy = true, minimum_release_age = "0s" }
gh = { version = "latest", lazy = true, minimum_release_age = "0s" }
copilot = { version = "latest", lazy = true, minimum_release_age = "0s" }
opencode = { version = "latest", lazy = true, minimum_release_age = "0s" }
playwright = { version = "latest", lazy = true, minimum_release_age = "0s" }
pi = { version = "latest", lazy = true, minimum_release_age = "0s" }
oh-my-pi = { version = "latest", lazy = true, minimum_release_age = "0s" }
grok = { version = "latest", lazy = true, minimum_release_age = "0s" }
ghui = { version = "latest", lazy = true, minimum_release_age = "0s" }
hunk = { version = "latest", lazy = true, minimum_release_age = "0s" }
hey-cli = { version = "latest", lazy = true, minimum_release_age = "0s" }
ori = { version = "latest", lazy = true, minimum_release_age = "0s" }
