;; Auto-generated by Omarchy theme engine
;; DO NOT EDIT DIRECTLY -- changes will be overwritten on theme change

(setq omarchy-theme-bg "{{ bg }}")
(setq omarchy-theme-fg "{{ fg }}")
(setq omarchy-theme-accent "{{ accent }}")
(setq omarchy-theme-red "{{ red }}")
(setq omarchy-theme-green "{{ green }}")
(setq omarchy-theme-yellow "{{ yellow }}")
(setq omarchy-theme-blue "{{ blue }}")
(setq omarchy-theme-magenta "{{ magenta }}")
(setq omarchy-theme-cyan "{{ cyan }}")

(defun omarchy/apply-theme-to-frame (frame)
  "Ensure graphic emacsclient frames evaluate full 24-bit GUI theme colors."
  (with-selected-frame frame
    (when (display-graphic-p frame)
      (set-face-attribute 'default frame :background "{{ bg }}" :foreground "{{ fg }}"))))

;; Handle daemon client frames & standalone GUI instances
(if (daemonp)
    (add-hook 'after-make-frame-functions #'omarchy/apply-theme-to-frame)
  (omarchy/apply-theme-to-frame (selected-frame)))

(provide 'omarchy-theme)
