/* Generated by Omarchy from the active theme. */

@media (prefers-color-scheme: {{ theme_type }}) {
  /* Nautilus still uses these libadwaita compatibility names in app CSS. */
  @define-color accent_color {{ accent }};
  @define-color accent_bg_color {{ accent }};
  @define-color accent_fg_color {{ accent_foreground }};
  @define-color destructive_color {{ red }};
  @define-color destructive_bg_color {{ red }};
  @define-color destructive_fg_color {{ red_foreground }};
  @define-color success_color {{ green }};
  @define-color success_bg_color {{ green }};
  @define-color success_fg_color {{ green_foreground }};
  @define-color warning_color {{ yellow }};
  @define-color warning_bg_color {{ yellow }};
  @define-color warning_fg_color {{ yellow_foreground }};
  @define-color error_color {{ red }};
  @define-color error_bg_color {{ red }};
  @define-color error_fg_color {{ red_foreground }};
  @define-color window_bg_color {{ background }};
  @define-color window_fg_color {{ foreground }};
  @define-color view_bg_color {{ background }};
  @define-color view_fg_color {{ foreground }};
  @define-color headerbar_bg_color {{ dark_background }};
  @define-color headerbar_fg_color {{ foreground }};
  @define-color headerbar_backdrop_color {{ darker_background }};
  @define-color sidebar_bg_color {{ dark_background }};
  @define-color sidebar_fg_color {{ foreground }};
  @define-color sidebar_backdrop_color {{ darker_background }};
  @define-color card_bg_color {{ lighter_background }};
  @define-color card_fg_color {{ foreground }};
  @define-color dialog_bg_color {{ lighter_background }};
  @define-color dialog_fg_color {{ foreground }};
  @define-color popover_bg_color {{ lighter_background }};
  @define-color popover_fg_color {{ foreground }};

  :root {
    /* Libadwaita derives the standalone *-color values from these backgrounds. */
    --accent-bg-color: {{ accent }};
    --accent-fg-color: {{ accent_foreground }};

    --destructive-bg-color: {{ red }};
    --destructive-fg-color: {{ red_foreground }};
    --success-bg-color: {{ green }};
    --success-fg-color: {{ green_foreground }};
    --warning-bg-color: {{ yellow }};
    --warning-fg-color: {{ yellow_foreground }};
    --error-bg-color: {{ red }};
    --error-fg-color: {{ red_foreground }};

    --window-bg-color: {{ background }};
    --window-fg-color: {{ foreground }};
    --view-bg-color: {{ background }};
    --view-fg-color: {{ foreground }};

    --headerbar-bg-color: {{ dark_background }};
    --headerbar-fg-color: {{ foreground }};
    --headerbar-backdrop-color: {{ darker_background }};

    --sidebar-bg-color: {{ dark_background }};
    --sidebar-fg-color: {{ foreground }};
    --sidebar-backdrop-color: {{ darker_background }};

    --secondary-sidebar-bg-color: {{ darker_background }};
    --secondary-sidebar-fg-color: {{ foreground }};
    --secondary-sidebar-backdrop-color: {{ darker_background }};

    --card-bg-color: {{ lighter_background }};
    --card-fg-color: {{ foreground }};
    --dialog-bg-color: {{ lighter_background }};
    --dialog-fg-color: {{ foreground }};
    --popover-bg-color: {{ lighter_background }};
    --popover-fg-color: {{ foreground }};

    --overview-bg-color: {{ dark_background }};
    --overview-fg-color: {{ foreground }};
    --thumbnail-bg-color: {{ lighter_background }};
    --thumbnail-fg-color: {{ foreground }};
    --active-toggle-bg-color: {{ accent }};
    --active-toggle-fg-color: {{ accent_foreground }};
  }
}
