/* Generated by Omarchy theme — do not edit by hand.
   Translucent shade/backdrop colors are intentionally left at Adwaita's
   mode defaults (they are overlays, not palette colors). */
:root {
  /* Backgrounds */
  --window-bg-color: {{ background }};
  --view-bg-color: {{ background }};
  --sidebar-bg-color: {{ dark_background }};
  --secondary-sidebar-bg-color: {{ dark_background }};
  --headerbar-bg-color: {{ background }};
  --card-bg-color: {{ lighter_background }};
  --dialog-bg-color: {{ background }};
  --popover-bg-color: {{ lighter_background }};
  --thumbnail-bg-color: {{ background }};
  --overview-bg-color: {{ background }};

  /* Foregrounds */
  --window-fg-color: {{ foreground }};
  --view-fg-color: {{ foreground }};
  --sidebar-fg-color: {{ foreground }};
  --secondary-sidebar-fg-color: {{ foreground }};
  --headerbar-fg-color: {{ foreground }};
  --card-fg-color: {{ foreground }};
  --dialog-fg-color: {{ foreground }};
  --popover-fg-color: {{ foreground }};
  --thumbnail-fg-color: {{ foreground }};
  --overview-fg-color: {{ foreground }};

  /* Accent */
  --accent-bg-color: {{ accent }};
  --accent-color: {{ accent }};
  --accent-fg-color: {{ background }};
  --banner-color: {{ accent }};

  /* Borders */
  --border-color: {{ muted }};
  --headerbar-border-color: {{ muted }};
  --sidebar-border-color: {{ muted }};
  --secondary-sidebar-border-color: {{ muted }};
  --slider-border-color: {{ muted }};

  /* Toggles */
  --active-toggle-bg-color: {{ accent }};
  --active-toggle-fg-color: {{ background }};

  /* Status colors */
  --destructive-bg-color: {{ red }};
  --destructive-color: {{ red }};
  --destructive-fg-color: {{ background }};
  --success-bg-color: {{ green }};
  --success-color: {{ green }};
  --success-fg-color: {{ background }};
  --warning-bg-color: {{ yellow }};
  --warning-color: {{ yellow }};
  --warning-fg-color: {{ background }};
  --error-bg-color: {{ red }};
  --error-color: {{ red }};
  --error-fg-color: {{ background }};
}
