{
  "base": "github-{{ mode }}-default",
  "background": "{{ background }}",
  "panel": "{{ dark_background }}",
  "panelAlt": "{{ lighter_background }}",
  "border": "{{ muted }}",
  "accent": "{{ accent }}",
  "accentMuted": "{{ mix accent background 50% }}",
  "text": "{{ foreground }}",
  "muted": "{{ dark_foreground }}",
  "addedBg": "{{ mix background green 15% }}",
  "removedBg": "{{ mix background red 15% }}",
  "movedAddedBg": "{{ mix background cyan 15% }}",
  "movedRemovedBg": "{{ mix background magenta 15% }}",
  "contextBg": "{{ background }}",
  "addedContentBg": "{{ mix background green 32% }}",
  "removedContentBg": "{{ mix background red 32% }}",
  "contextContentBg": "{{ background }}",
  "addedSignColor": "{{ green }}",
  "removedSignColor": "{{ red }}",
  "lineNumberBg": "{{ dark_background }}",
  "lineNumberFg": "{{ dark_foreground }}",
  "selectedHunk": "{{ selection }}",
  "badgeAdded": "{{ green }}",
  "badgeRemoved": "{{ red }}",
  "badgeNeutral": "{{ muted }}",
  "fileNew": "{{ green }}",
  "fileDeleted": "{{ red }}",
  "fileRenamed": "{{ blue }}",
  "fileModified": "{{ yellow }}",
  "fileUntracked": "{{ cyan }}",
  "noteBorder": "{{ accent }}",
  "noteBackground": "{{ lighter_background }}",
  "noteTitleBackground": "{{ accent }}",
  "noteTitleText": "{{ background }}",
  "syntaxScopes": {
    "comment": "{{ muted }}",
    "keyword": "{{ magenta }}",
    "string": "{{ green }}",
    "entity.name.function": "{{ blue }}",
    "constant.numeric": "{{ orange }}",
    "variable": "{{ foreground }}"
  }
}
