{
  "name": "Omarchy",
  "author": "Omarchy contributors",
  "variables": {
    "om_background": "{{ background }}",
    "om_surface": "{{ lighter_background }}",
    "om_foreground": "{{ foreground }}",
    "om_dim": "{{ dark_foreground }}",
    "om_muted": "{{ muted }}",
    "om_accent": "{{ accent }}",
    "om_selection": "{{ selection_background }}",
    "om_red": "{{ red }}",
    "om_orange": "{{ orange }}",
    "om_yellow": "{{ yellow }}",
    "om_green": "{{ green }}",
    "om_cyan": "{{ cyan }}",
    "om_blue": "{{ blue }}",
    "om_magenta": "{{ magenta }}",
    "redish": "{{ red }}",
    "orangish": "{{ orange }}",
    "yellowish": "{{ yellow }}",
    "greenish": "{{ green }}",
    "cyanish": "{{ cyan }}",
    "bluish": "{{ blue }}",
    "purplish": "{{ magenta }}",
    "pinkish": "{{ magenta }}"
  },
  "globals": {
    "background": "var(om_background)",
    "foreground": "var(om_foreground)",
    "caret": "var(om_accent)",
    "accent": "var(om_accent)",
    "selection": "var(om_selection)",
    "selection_foreground": "{{ selection_foreground }}",
    "inactive_selection": "color(var(om_selection) alpha(0.5))",
    "line_highlight": "var(om_surface)",
    "gutter": "var(om_background)",
    "gutter_foreground": "var(om_muted)",
    "gutter_foreground_highlight": "var(om_foreground)",
    "line_diff_added": "var(om_green)",
    "line_diff_modified": "var(om_yellow)",
    "line_diff_deleted": "var(om_red)",
    "highlight": "var(om_accent)",
    "find_highlight": "var(om_yellow)",
    "find_highlight_foreground": "var(om_background)",
    "brackets_foreground": "var(om_accent)",
    "tags_foreground": "var(om_accent)",
    "misspelling": "var(om_red)",
    "minimap_border": "var(om_muted)",
    "guide": "var(om_surface)",
    "active_guide": "var(om_muted)"
  },
  "rules": [
    { "name": "Comments", "scope": "comment", "foreground": "var(om_muted)" },
    { "name": "Punctuation", "scope": "punctuation", "foreground": "var(om_dim)" },
    { "name": "Strings", "scope": "string", "foreground": "var(om_green)" },
    { "name": "Escape sequences", "scope": "constant.character.escape", "foreground": "var(om_cyan)" },
    { "name": "Numbers", "scope": "constant.numeric", "foreground": "var(om_orange)" },
    { "name": "Constants", "scope": "constant", "foreground": "var(om_orange)" },
    { "name": "Language constants", "scope": "constant.language", "foreground": "var(om_orange)" },
    { "name": "Keywords", "scope": "keyword", "foreground": "var(om_magenta)" },
    { "name": "Control keywords", "scope": "keyword.control", "foreground": "var(om_magenta)" },
    { "name": "Declarations", "scope": "keyword.declaration", "foreground": "var(om_magenta)" },
    { "name": "Operators", "scope": "keyword.operator", "foreground": "var(om_cyan)" },
    { "name": "Types and storage", "scope": "storage.type, storage.modifier", "foreground": "var(om_yellow)" },
    { "name": "Declared entities", "scope": "entity.name", "foreground": "var(om_yellow)" },
    { "name": "Functions", "scope": "entity.name.function", "foreground": "var(om_blue)" },
    { "name": "Types", "scope": "entity.name.type, entity.name.class, entity.name.struct, entity.name.interface, entity.other.inherited-class", "foreground": "var(om_yellow)" },
    { "name": "Namespaces", "scope": "entity.name.namespace, entity.name.module", "foreground": "var(om_cyan)" },
    { "name": "Variables", "scope": "variable", "foreground": "var(om_foreground)" },
    { "name": "Built-in variables", "scope": "variable.language", "foreground": "var(om_red)" },
    { "name": "Parameters", "scope": "variable.parameter", "foreground": "var(om_orange)" },
    { "name": "Function calls", "scope": "variable.function", "foreground": "var(om_blue)" },
    { "name": "Properties", "scope": "variable.other.member", "foreground": "var(om_cyan)" },
    { "name": "Library names", "scope": "support.function, support.class, support.type", "foreground": "var(om_blue)" },
    { "name": "Tags", "scope": "entity.name.tag", "foreground": "var(om_red)" },
    { "name": "Attributes", "scope": "entity.other.attribute-name", "foreground": "var(om_yellow)" },
    { "name": "Markdown headings", "scope": "markup.heading, entity.name.section", "foreground": "var(om_accent)", "font_style": "bold" },
    { "name": "Markdown links", "scope": "markup.underline.link, markup.link, string.other.link", "foreground": "var(om_blue)", "font_style": "underline" },
    { "name": "Markdown code", "scope": "markup.raw, markup.inline.raw", "foreground": "var(om_green)" },
    { "name": "Markdown quotes", "scope": "markup.quote", "foreground": "var(om_muted)" },
    { "name": "Diff additions", "scope": "markup.inserted", "foreground": "var(om_green)" },
    { "name": "Diff deletions", "scope": "markup.deleted", "foreground": "var(om_red)" },
    { "name": "Diff changes", "scope": "markup.changed", "foreground": "var(om_yellow)" },
    { "name": "Invalid", "scope": "invalid", "foreground": "var(om_red)", "font_style": "underline" },
    { "name": "Deprecated", "scope": "invalid.deprecated", "foreground": "var(om_muted)", "font_style": "underline" }
  ]
}
