;;; omarchy-colors.el --- Auto-generated by Omarchy theme engine -*- lexical-binding: t -*-
;;; DO NOT EDIT DIRECTLY -- changes will be overwritten on theme change

(setq omarchy-color-accent "{{ accent }}")
(setq omarchy-color-cursor "{{ cursor }}")
(setq omarchy-color-fg "{{ fg }}")
(setq omarchy-color-bg "{{ bg }}")
(setq omarchy-color-sel-fg "{{ selection_foreground }}")
(setq omarchy-color-sel-bg "{{ selection_background }}")

(setq omarchy-color-black "{{ color0 }}")
(setq omarchy-color-red "{{ red }}")
(setq omarchy-color-green "{{ green }}")
(setq omarchy-color-yellow "{{ yellow }}")
(setq omarchy-color-blue "{{ blue }}")
(setq omarchy-color-magenta "{{ magenta }}")
(setq omarchy-color-cyan "{{ cyan }}")
(setq omarchy-color-white "{{ color7 }}")

(setq omarchy-color-bright-black "{{ color8 }}")
(setq omarchy-color-bright-red "{{ bright_red }}")
(setq omarchy-color-bright-green "{{ bright_green }}")
(setq omarchy-color-bright-yellow "{{ bright_yellow }}")
(setq omarchy-color-bright-blue "{{ bright_blue }}")
(setq omarchy-color-bright-magenta "{{ bright_magenta }}")
(setq omarchy-color-bright-cyan "{{ bright_cyan }}")
(setq omarchy-color-bright-white "{{ bright_foreground }}")

(setq omarchy-is-light (string= "{{ mode }}" "light"))

(provide 'omarchy-colors)
;;; omarchy-colors.el ends here
