{
  "$schema": "https://opencode.ai/theme.json",
  "theme": {
    "primary": "{{ accent }}",
    "secondary": "{{ cyan }}",
    "accent": "{{ accent }}",
    "error": "{{ red }}",
    "warning": "{{ yellow }}",
    "success": "{{ green }}",
    "info": "{{ blue }}",
    "text": "{{ foreground }}",
    "textMuted": "{{ muted }}",
    "selectedListItemText": "{{ selection_foreground }}",
    "background": "{{ background }}",
    "backgroundPanel": "{{ mix background foreground 5% }}",
    "backgroundElement": "{{ mix background foreground 9% }}",
    "backgroundMenu": "{{ mix background foreground 6% }}",
    "border": "{{ mix background foreground 18% }}",
    "borderActive": "{{ muted }}",
    "borderSubtle": "{{ mix background foreground 12% }}",
    "diffAdded": "{{ green }}",
    "diffRemoved": "{{ red }}",
    "diffContext": "{{ muted }}",
    "diffHunkHeader": "{{ muted }}",
    "diffHighlightAdded": "{{ green }}",
    "diffHighlightRemoved": "{{ red }}",
    "diffAddedBg": "{{ mix background green 14% }}",
    "diffRemovedBg": "{{ mix background red 14% }}",
    "diffContextBg": "{{ background }}",
    "diffLineNumber": "{{ mix background foreground 25% }}",
    "diffAddedLineNumberBg": "{{ mix background green 8% }}",
    "diffRemovedLineNumberBg": "{{ mix background red 8% }}",
    "markdownText": "{{ foreground }}",
    "markdownHeading": "{{ bright_foreground }}",
    "markdownLink": "{{ blue }}",
    "markdownLinkText": "{{ cyan }}",
    "markdownCode": "{{ cyan }}",
    "markdownBlockQuote": "{{ muted }}",
    "markdownEmph": "{{ yellow }}",
    "markdownStrong": "{{ bright_foreground }}",
    "markdownHorizontalRule": "{{ mix background foreground 20% }}",
    "markdownListItem": "{{ accent }}",
    "markdownListEnumeration": "{{ cyan }}",
    "markdownImage": "{{ blue }}",
    "markdownImageText": "{{ cyan }}",
    "markdownCodeBlock": "{{ foreground }}",
    "syntaxComment": "{{ muted }}",
    "syntaxKeyword": "{{ magenta }}",
    "syntaxFunction": "{{ blue }}",
    "syntaxVariable": "{{ foreground }}",
    "syntaxString": "{{ green }}",
    "syntaxNumber": "{{ orange }}",
    "syntaxType": "{{ yellow }}",
    "syntaxOperator": "{{ cyan }}",
    "syntaxPunctuation": "{{ muted }}",
    "thinkingOpacity": 0.6
  }
}
