{
  "label": "Omarchy",
  "colors": {
    "bg": "{{ background }}",
    "bg-accent": "{{ mix background foreground 3% }}",
    "bg-elevated": "{{ mix background foreground 6% }}",
    "bg-hover": "{{ mix background foreground 10% }}",
    "bg-muted": "{{ mix background foreground 10% }}",
    "bg-content": "{{ mix background foreground 2% }}",
    "card": "{{ mix background foreground 5% }}",
    "card-foreground": "{{ bright_foreground }}",
    "card-highlight": "rgba({{ foreground_rgb }}, 0.04)",
    "popover": "{{ mix background foreground 8% }}",
    "popover-foreground": "{{ bright_foreground }}",
    "panel": "{{ background }}",
    "panel-strong": "{{ mix background foreground 6% }}",
    "panel-hover": "{{ mix background foreground 10% }}",
    "chrome": "rgba({{ background_rgb }}, 0.96)",
    "chrome-strong": "rgba({{ background_rgb }}, 0.98)",
    "text": "{{ foreground }}",
    "text-strong": "{{ bright_foreground }}",
    "chat-text": "{{ foreground }}",
    "muted": "{{ mix foreground background 40% }}",
    "muted-strong": "{{ mix foreground background 25% }}",
    "muted-foreground": "{{ mix foreground background 40% }}",
    "border": "{{ mix background foreground 12% }}",
    "border-strong": "{{ mix background foreground 22% }}",
    "border-hover": "{{ mix background foreground 35% }}",
    "input": "{{ mix background foreground 12% }}",
    "ring": "{{ accent }}",
    "accent": "{{ accent }}",
    "accent-hover": "{{ mix accent bright_foreground 15% }}",
    "accent-muted": "{{ accent }}",
    "accent-subtle": "rgba({{ accent_rgb }}, 0.12)",
    "accent-foreground": "{{ background }}",
    "accent-glow": "rgba({{ accent_rgb }}, 0.2)",
    "primary": "{{ accent }}",
    "primary-foreground": "{{ background }}",
    "secondary": "{{ mix background foreground 6% }}",
    "secondary-foreground": "{{ bright_foreground }}",
    "accent-2": "{{ yellow }}",
    "accent-2-muted": "rgba({{ yellow_rgb }}, 0.7)",
    "accent-2-subtle": "rgba({{ yellow_rgb }}, 0.12)",
    "destructive": "{{ red }}",
    "destructive-foreground": "{{ background }}",
    "danger": "{{ red }}",
    "danger-muted": "rgba({{ red_rgb }}, 0.7)",
    "danger-subtle": "rgba({{ red_rgb }}, 0.12)",
    "focus": "rgba({{ accent_rgb }}, 0.18)",
    "focus-ring": "0 0 0 2px var(--bg), 0 0 0 3px color-mix(in srgb, var(--ring) 75%, transparent)",
    "focus-glow": "0 0 0 2px var(--bg), 0 0 0 3px var(--ring), 0 0 16px var(--accent-glow)",
    "font-body": "system-ui, sans-serif",
    "font-display": "system-ui, sans-serif",
    "mono": "ui-monospace, monospace",
    "grid-line": "rgba({{ foreground_rgb }}, 0.04)"
  }
}
