{
  "Colors": {
    "Black": "{{ darker_background }}",
    "Title": "{{ dark_background }}",
    "Background": "{{ dark_background }}",
    "WindowBorder": "{{ darker_background }}",
    "Foldout": "{{ darker_background }}",
    "Input": "{{ darker_background }}",
    "InputOutline": "{{ mix lighter_background foreground 10% }}",
    "Recessed": "{{ mix dark_background background 50% }}",
    "Panel": "{{ background }}",
    "Header": "{{ lighter_background }}",
    "Dropdown": "{{ mix lighter_background foreground 10% }}",
    "DropdownOutline": "{{ mix lighter_background foreground 20% }}",
    "Hover": "{{ mix lighter_background foreground 30% }}",
    "Hover2": "{{ mix background foreground 50% }}",
    "White": "{{ bright_foreground }}",
    "White25": "{{ bright_foreground }}40",
    "Highlight": "{{ accent }}",
    "Primary": "{{ accent }}",
    "PrimaryHover": "{{ mix accent foreground 20% }}",
    "PrimaryPress": "{{ mix accent background 30% }}",
    "Secondary": "{{ mix lighter_background foreground 10% }}",
    "Foreground": "{{ foreground }}",
    "ForegroundHover": "{{ bright_foreground }}",
    "ForegroundInverted": "{{ darker_background }}",
    "ForegroundHeader": "{{ light_foreground }}",
    "Select": "{{ accent }}",
    "SelectInactive": "{{ selection }}",
    "SelectParent": "{{ mix background selection 50% }}",
    "SelectHover": "{{ background }}",
    "Notifications": "{{ lighter_background }}",
    "AccentBlue": "{{ blue }}",
    "AccentPurple": "{{ magenta }}",
    "AccentPink": "{{ bright_magenta }}",
    "AccentRed": "{{ red }}",
    "AccentOrange": "{{ orange }}",
    "AccentYellow": "{{ yellow }}",
    "AccentGreen": "{{ green }}",
    "AccentBrown": "{{ brown }}",
    "AccentBlack": "{{ background }}",
    "AccentGray": "{{ dark_foreground }}",
    "AccentWhite": "{{ bright_foreground }}",
    "AccentFolder": "{{ mix yellow brown 40% }}",
    "Warning": "{{ yellow }}",
    "Error": "{{ red }}",
    "Success": "{{ green }}"
  }
}
