# The Spark firmware clears memory as it is freed, and Limine frees the ~124 GB
# it claimed before starting a UKI, leaving the screen black for ~20 seconds.
# Boot the kernel directly until Limine stops that, then remove this and rebuild:
# https://github.com/Limine-Bootloader/Limine/issues/673
limine_config_dir=${OMARCHY_LIMINE_CONFIG_DIR:-/etc/limine-entry-tool.d}

if omarchy-hw-dgx-spark; then
  mkdir -p "$limine_config_dir"
  # Named to sort after omarchy-uki.conf, whose ENABLE_UKI=yes this overrides.
  cat >"$limine_config_dir/zz-omarchy-dgx-spark.conf" <<'CONF'
# Generated by Omarchy for the NVIDIA DGX Spark: boot without a UKI to avoid a
# 20-second firmware delay. Remove once Limine fixes
# https://github.com/Limine-Bootloader/Limine/issues/673
ENABLE_UKI=no
CONF
fi
