# shellcheck shell=bash

# Shared validation and rendering for omarchy-managed. This file is sourced by
# the command and its tests; it does not perform privileged work on its own.

OMARCHY_MANAGED_USERNAME_PATTERN='^[a-z_][a-z0-9_-]{0,31}$'
OMARCHY_MANAGED_PROXY_PORT_MIN=42000
OMARCHY_MANAGED_PROXY_PORT_MAX=42999

managed_account_username_valid() {
  local username=$1

  [[ $username =~ $OMARCHY_MANAGED_USERNAME_PATTERN ]] || return 1
  [[ $username != "root" && $username != "nobody" ]]
}

managed_account_site_normalize() {
  local input=${1,,}
  local authority host label scheme

  # Website entries are host allowlists. Accept a pasted URL for convenience,
  # but deliberately discard its path: HTTPS paths are encrypted from a proxy.
  input=${input#"${input%%[![:space:]]*}"}
  input=${input%"${input##*[![:space:]]}"}
  [[ -n $input && $input != *[[:space:]]* ]] || return 1

  if [[ $input == *"://"* ]]; then
    scheme=${input%%://*}
    [[ $scheme == "http" || $scheme == "https" ]] || return 1
    authority=${input#*://}
  else
    authority=$input
  fi

  authority=${authority%%[/?#]*}
  [[ -n $authority && $authority != *"@"* ]] || return 1

  # IPv6 literals and arbitrary ports are not website identities. Squid is
  # separately limited to ports 80 and 443.
  [[ $authority != "["* && $authority != *"]" ]] || return 1
  host=${authority%%:*}
  [[ $authority == "$host" || $authority == "$host:80" || $authority == "$host:443" ]] || return 1

  [[ $host == "*."* ]] && host=${host#\*.}
  host=${host#.}
  host=${host%.}
  [[ ${#host} -le 253 && $host == *.* ]] || return 1
  [[ $host != "localhost" && $host != *.localhost && $host != *.local ]] || return 1
  [[ $host != *..* ]] || return 1
  [[ ! $host =~ ^[0-9.]+$ ]] || return 1

  local IFS=.
  read -ra labels <<<"$host"
  for label in "${labels[@]}"; do
    [[ -n $label && ${#label} -le 63 ]] || return 1
    [[ $label =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
  done

  # A leading dot is Squid's dstdomain spelling for the host and all of its
  # subdomains. This is what people expect when allowing a website.
  printf '.%s\n' "$host"
}

managed_account_allowlist_add() {
  local allowlist=$1
  shift
  local normalized=() site tmp

  for site in "$@"; do
    site=$(managed_account_site_normalize "$site") || return 1
    normalized+=("$site")
  done

  tmp=$(mktemp "${allowlist}.new.XXXXXX") || return 1
  {
    [[ -f $allowlist ]] && cat "$allowlist"
    printf '%s\n' "${normalized[@]}"
  } | sed '/^$/d' | sort -u >"$tmp"
  chmod 0644 "$tmp"
  mv -f -- "$tmp" "$allowlist"
}

managed_account_allowlist_remove() {
  local allowlist=$1
  shift
  local normalized=() site tmp

  for site in "$@"; do
    site=$(managed_account_site_normalize "$site") || return 1
    normalized+=("$site")
  done

  tmp=$(mktemp "${allowlist}.new.XXXXXX") || return 1
  if [[ -f $allowlist ]]; then
    awk -v removals="$(printf '%s\n' "${normalized[@]}")" '
      BEGIN { count = split(removals, entries, "\n"); for (i = 1; i <= count; i++) remove[entries[i]] = 1 }
      !remove[$0]
    ' "$allowlist" >"$tmp"
  fi
  chmod 0644 "$tmp"
  mv -f -- "$tmp" "$allowlist"
}

managed_account_render_squid_config() {
  local username=$1
  local port=$2
  local allowlist=$3

  managed_account_username_valid "$username" || return 1
  (( port >= OMARCHY_MANAGED_PROXY_PORT_MIN && port <= OMARCHY_MANAGED_PROXY_PORT_MAX )) || return 1
  [[ $allowlist == /* ]] || return 1

  cat <<EOF
# Generated by omarchy-managed. Edit the allowlist with omarchy managed.
http_port 127.0.0.1:$port

acl local_client src 127.0.0.1/32
acl allowed_ports port 80 443
acl ssl_ports port 443
acl connect method CONNECT
acl allowed_sites dstdomain "$allowlist"
acl blocked_destinations dst 0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16 224.0.0.0/3 ::/128 ::1/128 fc00::/7 fe80::/10 ff00::/8

http_access deny !allowed_ports
http_access deny connect !ssl_ports
http_access deny blocked_destinations
http_access allow local_client allowed_sites
http_access deny all

cache deny all
access_log none
cache_store_log none
cache_log /dev/null
pid_filename /run/omarchy-managed-proxy-$username/squid.pid
coredump_dir /tmp
forwarded_for delete
EOF
}

managed_account_render_nft_config() {
  local uid port

  cat <<'EOF'
delete table inet omarchy_managed_accounts
add table inet omarchy_managed_accounts
add chain inet omarchy_managed_accounts output { type filter hook output priority -10; policy accept; }
EOF

  while read -r uid port; do
    [[ $uid =~ ^[0-9]+$ && $port =~ ^[0-9]+$ ]] || return 1
    (( uid >= 1000 && uid != 65534 )) || return 1
    (( port >= OMARCHY_MANAGED_PROXY_PORT_MIN && port <= OMARCHY_MANAGED_PROXY_PORT_MAX )) || return 1

    printf 'add rule inet omarchy_managed_accounts output meta skuid %s ip daddr 127.0.0.1 tcp dport %s accept\n' "$uid" "$port"
    printf 'add rule inet omarchy_managed_accounts output meta skuid %s reject\n' "$uid"
  done
}
